const CAMPAIGN_02_RECAPS = [
	{
		id: 'session-001',
		title: 'Introduction',
		date: '2025-04-12',
		content: `
		<p>The story of our five heroes begins, as many do, on a road leading toward a town.</p>
		<p>But this is no well-traveled path of cobblestones and dust - instead, it winds through a thick tangle of knee-high weeds and scattered trees, draped in the vibrant green of a subtropical forest. The air is heavy with the scent of life and growth, and the sound of distant creatures echoes beneath the canopy.</p>
		<p>Our heroes are quite the unlikely bunch - a rare mix of races and origins - but they travel together in good spirits, friendly and merry, sharing tales and learning more of one another with each step.</p>
		<p>They have met before, here and there. Once or twice as allies, perhaps once or twice as obstacles to each other's paths. Yet none of that seems to matter now. Whatever reasons brought them together - whether shared cause or secret ambition - they move forward as one, at least for now.</p>
		<p>Now, one by one, let us see who they are.</p>

		<p><h3>Olek, the Aasimar Paladin of Helm</h3></p>

		<p>He is devotion given form - an angelic soul clad in armor, kind and just, friendly and ever ready for conversation. [ENTITY:character:Olek] is honorable to his very core, though humble in his ways, never one to boast or seek glory.</p>
		<p>His story is unlike any other. As a child, he and his sibling were raised not by kin of their own kind, but by wolves, deep within the forest. How they came to be there, he cannot say. The memory is lost to time or fate. But the pack was family, and he knew love in fur and fang.</p>
		<p>Then came the day of fire and chaos - a savage raid by orcs, goblins, and fouler things still. In the desperate struggle, his pack urged the siblings to flee. In the confusion, they were separated. [ENTITY:character:Olek] wandered for days beneath the trees, searching for his family, for his brother or sister, for anyone.</p>
        <p>And then, when all hope seemed lost, fate intervened. A celestial being descended - radiant and awe-inspiring, not Helm himself but a servant of his will, a divine entity bound closely to the God of Guardians. With a voice like distant thunder wrapped in warmth, the being offered [ENTITY:character:Olek] a pact, with one charge: <strong>Help as many as you can. Save those in need. Whatever you may do, walk forward with the teachings of our Father. Never stray. Never falter.</strong></p>
        <p>[ENTITY:character:Olek] accepted.</p>
        <p>He reached the town of [ENTITY:location:Brindol], where he offered help wherever it was needed. He stood beside other paladins of Helm, worked to defend the weak, and forged both likely and unlikely bonds. And now, he finds himself walking beside four others, toward the distant town of [ENTITY:location:Drellin\'s Ferry], with justice and goodness lighting his path.</p>
        <p>Whatever awaits them there, [ENTITY:character:Olek] walks forward with purpose - for the lost, for the helpless, for the ideals he now embodies.</p>
        
        <p><h3>Norr, the Sorcerer with Dragon's Blood</h3></p>
        
        <p>[ENTITY:character:Norr], like so many other gifted children born into this world, did not have an easy start in life. Born into a poor family, with a father who enjoyed his drink a bit too much, and a mother unable to defend herself or her daughter, [ENTITY:character:Norr] learned early to keep quiet and keep to herself.</p>
        <p>She was beautiful, even as a child, and a strange, mysterious energy seemed to surround her. Drawing attention was never ideal - especially not in a household like hers. Her parents, frightened and unsure of what she was becoming, kept her gifts hidden from the world.</p>
        <p>As fate often does, it intervened on a stormy, rain-soaked night. While searching for shelter from the downpour, [ENTITY:character:Norr] stumbled upon a terrible scene: a fair Lady, beset by bandits. [ENTITY:character:Norr] panicked, frozen in fear, uncertain of how to help. But then, in a flash of lightning everything shifted.</p>
        <p>The lady was never truly in danger. Magic poured out of her in powerful waves, and the bandits stood no chance.</p>
        <p>Awestruck, [ENTITY:character:Norr] stepped closer, throwing caution to the wind. There was something familiar between them - something felt rather than seen. They were alike, somehow. They both knew it.</p>
        <p>The lady introduced herself as [ENTITY:npc:Zella], and she listened - truly listened - to [ENTITY:character:Norr]'s story. Her struggles, her fears, the confusion that had shadowed her life. And then [ENTITY:npc:Zella] made an offer: to take [ENTITY:character:Norr] under her wing and teach her the ways of magic.</p>
        <p>It was a painful decision. To leave her family and everything she had known behind, or to remain and live forever as only half of herself. But the excitement - the longing to understand what she was - overwhelmed her doubt. She went with [ENTITY:npc:Zella].</p>
        <p>They spent years together. [ENTITY:npc:Zella] taught her everything she knew, drilled every bit of magical knowledge into [ENTITY:character:Norr]'s mind. When there was nothing left to teach, she sent her student onward - to [ENTITY:location:Luskan], to find the [ENTITY:guild:Arcane Brotherhood]. A place of boundless learning, where the magically gifted could find their path. A place, perhaps, to belong.</p>
        <p>[ENTITY:character:Norr] joined the Brotherhood but soon discovered that great institutions often hide terrible secrets. Together with a friend she made within its walls, she uncovered one such secret - a map leading to a great treasure. And together, they fled. The road led them to [ENTITY:location:Brindol].</p>
        <p>And so, we find [ENTITY:character:Norr] now, her secrets held tight behind guarded eyes, the stolen map close to her heart. Beside her walks her dearest companion, and three strange allies whose paths are now twined with hers. Together they journey to [ENTITY:location:Drellin\'s Ferry].</p>
        <p>The future, like magic, is uncertain. But [ENTITY:character:Norr] walks forward - beautiful, dangerous, and full of lightning.</p>
        
        <p><h3>Soshi, the Eladrin Wizard from the Feywilds</h3></p>
        
        <p>[ENTITY:character:Soshi] was not born in the world of mortals. As all fey creatures do, she was born in the [ENTITY:location:Feywilds] - magic giving her shape and form, infusing her with the changing seasons.</p>
        <p>By now, we know that fate plays a hand in the lives of all beings. Some say she wandered too close to a thin place in the weave, others whisper she was drawn through by the echoes of something calling her. Whatever the cause, [ENTITY:character:Soshi] crossed into the Material Plane as a child, stepping through unseen doors and emerging into the harsh, unforgiving port city of [ENTITY:location:Luskan].</p>
        <p>Alone, alien, and stripped of the familiar cadence of fey life, [ENTITY:character:Soshi] learned quickly that her joyful magic and dreamlike presence were of little use in this place. Life among mortals was different - here, power was survival, and magic was currency.</p>
        <p>Slowly, desire crawled through the cracks left by doubt and a wavering sense of self. Slowly, it made her forget what she was, where she came from, and what magic was supposed to be.</p>
        <p>[ENTITY:character:Soshi] buried herself in books. Arcane formulas, incantations, the elegant structure of wizardry - she consumed it all with the desperation of someone who had everything to prove. In time, her dedication was noticed. The [ENTITY:guild:Arcane Brotherhood], ever in search of useful minds, extended a hand. Desperate to belong, desperate to be powerful, she took it.</p>
        <p>But by now, we also know the Brotherhood isn't a place of fairytales. Its dark, twisted secrets came to light, terrifying [ENTITY:character:Soshi] - reminding her that some prices are too high to pay.</p>
        <p>And so, together with the only friend she managed to make in this unforgiving world, she stole a map - a way for them to survive in the wide, dangerous world beyond.</p>
        <p>Driven by regrets, desires, and ambition, longing for home and the joyful life she left behind, [ENTITY:character:Soshi] finds herself traveling with four other companions: her friend from the Brotherhood, and three others as different as night is from day.</p>
        <p>And so, we find [ENTITY:character:Soshi], her spellbook in hand and memories of the [ENTITY:location:Feywilds] stirring in her chest, walking the winding road to [ENTITY:location:Drellin\'s Ferry].</p>
        
        <p><h3>Kaedin, the Earth Genasi Echo Knight of the Shifting Fates</h3></p>
        
        <p>[ENTITY:character:Kaedin] was an unusual child in a very usual family. Born out of humans, in a small mining village blessed by a Dao genie, he lived a simple life. Clever, full of energy, and with trouble always finding him, [ENTITY:character:Kaedin] enjoyed his days, finding excitement in what others would consider mundane.</p>
        <p>He became fast friends with [ENTITY:npc:Thalos], the son of a deeply religious [ENTITY:race:Earth Genasi] family. They couldn't have been more different - [ENTITY:character:Kaedin] scoffed at tradition, finding it impractical, while [ENTITY:npc:Thalos] honored it in every word, every piece of clothing, every step. But their souls were alike, and together they spent their days chasing adventure, uncovering secrets, and exploring hidden tunnels.</p>
        <p>As we've become accustomed, fate decided to meddle once more. During their daily search for excitement, they discovered a new tunnel. Of course, giddy and chatty and bickering, they delved in with no caution taken, no trap detected - because what could go wrong in such a simple village?</p>
        <p>[ENTITY:npc:Thalos] stepped onto a pressure plate.</p>
        <p>That's all it took to shatter [ENTITY:character:Kaedin]'s life. That's all it took for him to lose his friend - for him to almost lose himself.</p>
        <p>[ENTITY:npc:Thalos] was nowhere to be found. Assumed dead by the village, with only his traditional garb left behind.</p>
        <p>[ENTITY:character:Kaedin] never gave up. He looked for him. He was sure his friend had been taken somewhere.</p>
        <p>As time passed, strange things started happening to [ENTITY:character:Kaedin]. Terrible visions would show themselves to him, accompanied by excruciating headaches. He could see himself living a thousand lives, fighting a hundred battles, speaking tongues he had never heard before. He understood - whatever took his friend gave him visions of his alternate lives.</p>
        <p>But through it all, he knew - whatever had taken [ENTITY:npc:Thalos] had left something in him. A connection. A thread.</p>
        <p>And where there is a thread, there is a trail.</p>
        <p>[ENTITY:character:Kaedin] left his village, left his life behind. He looked for answers in the only place he could think of - the shadowy tunnels where exiles lived. Among them, he found one that would speak with him: a wizened mage by the name of Verenn Yorr. Verenn found that he could help [ENTITY:character:Kaedin] master his new abilities, trained him in combat while teaching him how to harness his visions and use them to his own will.</p>
        <p>When all teachings were done, [ENTITY:character:Kaedin] adventured into the world. He joined a company of soldiers, learned what he could from them. But he never forgot. His friend was still out there, waiting to be found.</p>
        <p>In memory of [ENTITY:npc:Thalos], no matter what he wore, [ENTITY:character:Kaedin] always donned the traditional garb over. This way he would never forget. This way he would never stop looking.</p>
        <p>And now we find [ENTITY:character:Kaedin] on the road to [ENTITY:location:Drellin\'s Ferry], walking beside four unlikely companions. He keeps his past close and his mission closer - his eyes on the path ahead, and his soul reaching for the one left behind.</p>
        
        <p><h3>Bonnie, the Pixie Rogue full of mischief</h3></p>
        
        <p>Here we are - our fifth hero. So far, we've heard tales of lost families, fractured selves, and friends long gone - of longings for magic, regrets for what once was, and hopes for what could be. [ENTITY:character:Bonnie], however, is not like that.</p>
        <p>[ENTITY:character:Bonnie] is a fairy pixie born from the pure magic of the [ENTITY:location:Feywilds]. She had no real family - other fairies born like her could be considered one, but she never saw it that way. She had no home beyond trees and groves, caves and lakes. [ENTITY:character:Bonnie] lived her long life doing whatever she pleased, always with her trusted companion, friend, and what she would call family: [ENTITY:npc:Jacques], the antlered giant rat.</p>
        <p>Pixies are known to be a little mischievous, but rarely with a truly mean bone in them. [ENTITY:character:Bonnie], however, seems to have that particular trait in spades. She found joy in rule-breaking, in taking what wasn't hers. She enjoyed doing what she wanted, when she wanted, and nothing - absolutely nothing - could stand in her way.</p>
        <p>But ah, what [ENTITY:character:Bonnie] did not anticipate was that fate had plans for her, too. One lovely morning, while dodging a swarm of angry Summer Court Sprites, she ran headfirst into someone who had no business being this deep in the [ENTITY:location:Feywilds] - a Quickling by the name of [ENTITY:npc:Clyde]. Now, [ENTITY:character:Bonnie] didn't care for rules, and instead of reporting the trespasser, she befriended him.</p>
        <p>In time, the two caused a storm of chaos together. They broke rules, borrowed (as they called it) treasures, stirred up trouble wherever they went. Their lives were fast and bright, a whirlwind of trouble and laughter - until the consequences finally caught up.</p>
        <p>[ENTITY:npc:Clyde] was captured by the Sprites and dragged before Queen Titania herself. A spy, they claimed. Sent by the twisted Winter Queen. The sentence was swift: execution.</p>
        <p>What [ENTITY:character:Bonnie] never expected in her long, chaotic life was to care for someone other than [ENTITY:npc:Jacques]. But she did. So, she stepped forward, confessed to everything in a desperate attempt to save her friend.</p>
        <p>[ENTITY:npc:Clyde] was spared. [ENTITY:character:Bonnie] was not. Exiled to the mortal plane, cut off from the [ENTITY:location:Feywilds], with no way back. [ENTITY:npc:Clyde] was gone. Magic was... different now.</p>
        <p>But [ENTITY:character:Bonnie] was scrappy. She carved out a life in [ENTITY:location:Brindol], adapted to the strange new shape of her magic, and stayed close to [ENTITY:npc:Jacques] - even if he was quite a bit smaller now than he once was. She spent her time with the Thieves' Guild, either waiting for something better to come along or searching for a way back home.</p>
        <p>And maybe, just maybe, that something finally did.</p>
        <p>On an errand to reach [ENTITY:location:Drellin\'s Ferry], [ENTITY:character:Bonnie] finds herself traveling with four odd companions, and while she brings trouble and pranks to their lives, she also watches their backs in her own special way.</p>

		<hr>
		
        <p>[IMAGE:images/assets/campaign_002/locations/drellin_ferry.jpg::300px::true]Here we are at last, on the way to [ENTITY:location:Drellin\'s Ferry] with a crew of misfits - five people, all chasing something that might fulfill their hopes and dreams, or simply trying to stop the world from unraveling.</p>
        <p>Now that we're all caught up with our heroes' stories, let's see what happened on the road to [ENTITY:location:Drellin\'s Ferry]!  </p>
		`,

		// Format: [IMAGE:path/to/image.jpg:optional-caption:optional-width:optional-alignment]
		recap: `
        <p>Five strangers walk a path less traveled—through tangled weeds and whispering trees—toward the town of [ENTITY:location:Drellin\'s Ferry]. Though their footsteps fall in unison now, each of them carries a life shaped by fate, tragedy, and a desire for something more. They are unlikely allies, bound together by choice or chance, but united in purpose... for now.</p>

		<p>[ENTITY:character:Olek], a [ENTITY:class:Paladin] of Helm, walks with the calm strength of one touched by the divine. Raised by wolves, orphaned by war, and uplifted by a celestial being, his journey is one of service and steadfast honor. With a heart full of duty and a past veiled in fire, he brings light to the dark places they travel.</p>

		<p>Beside him walks [ENTITY:character:Norr], a [ENTITY:class:Sorcerer] touched by dragon's blood and haunted by a stolen map. Fleeing the shadows of the [ENTITY:guild:Arcane Brotherhood] with her closest companion, she guards her secrets with sharp wit and quiet strength. Her friend, [ENTITY:character:Soshi]—a Feyborn wizard who traded whimsy for power—shares in that escape, both burdened by the Brotherhood's darkness and driven by dreams of belonging.</p>

		<p>Then there's [ENTITY:character:Kaedin], the [ENTITY:subclass:Echo Knight] genasi who seeks a friend lost to a trap and a mystery buried in time. Haunted by visions of other lives and trained to wield them as weapons, he wears tradition on his sleeve and carries the past on his back, each step a search for answers that lie beyond the veil of fate.</p>

		<p>And finally, [ENTITY:character:Bonnie]—a [ENTITY:class:rogue] pixie exiled from the [ENTITY:location:Feywilds] for loving too deeply and breaking too many rules. With [ENTITY:npc:Jacques] the rat at her side and chaos in her wake, she hides a loyal heart beneath layers of mischief. Together, these five travel toward [ENTITY:location:Drellin\'s Ferry], carrying hope, grief, ambition, and mischief in equal measure. What awaits them on the road is still unwritten.</p>`,
	},
	{
		id: 'session-002',
		title: "001 - Towards Drellin's Ferry",
		date: '2025-04-12',
		content: `<p>We begin on the fourth day of travel. Afternoon has settled in, the sun still burning, the air hot and still. The lands of Elsir Vale have blurred by now - every town looks the same, and our heroes can no longer tell one from the next.</p>
        <p>[ENTITY:location:Drellin's Ferry] lies just a few miles ahead - both their destination and their long-awaited respite from the arduous road. Conversation has grown scarce. After four days on the road, there's little left to say, and even less to want beyond a soft bed and a hot meal. A small question here and there - "So you really don't know where a fey portal is?" - and the occasional mage hand prank: a flick of the forehead, a stone in a boot. And so, our weary party presses on.</p>
        <p>The road crests a low rise and dips into a dusty grove nestled in a shallow dell. An abandoned farmhouse, half-hidden behind trees, leans tiredly by the roadside. They've passed places like this before - but something about this one feels wrong.</p>
        <p>[ENTITY:character:Bonnie] tilts her head and hums, voice light but sharp. "<span class="dialogue">If I were a thief - and I'm not saying I am - this would be the perfect place for an ambush.</span>" The others glance around, unsure if she's being paranoid or perceptive.</p>
        <h3>The fight</h3>
        <p>Then they see it - the glint of mail behind the brush. Tall, fierce warriors. Hairy, with wide mouths and flat faces. Waiting patiently for unsuspecting prey.</p>
        <p>The fight is long. Dangerous. The enemies are many, and the road has drained our heroes. The terrain does them no favors - tall grass and wreckage obscure their view, and the foes come from all sides. But even in the chaos, they begin to move as one. Combos fly. Tactics form. Help is given before it's asked for.</p>
        <p>A true display of teamwork comes when they face the enemy captain. From afar, lightning sparks from [ENTITY:character:Norr]'s fingers, a bolt cutting through the air. Mirroring her motion, like twin sisters in perfect harmony, flames burst from [ENTITY:character:Soshi]'s hands, wrapping the lightning in fire. The bolt finds its mark just as [ENTITY:character:Kaedin]'s echo flickers into place beside the captain - his blade striking in tandem with [ENTITY:character:Olek]'s glowing club, one from the front, one from behind. And then [ENTITY:character:Bonnie], ever the performer, sheds crocodile tears as her dagger sinks deep in his heart, in a flash of glinting mischief and precision. There is nothing left of him. In the wake of such relentless force, a voice cries out from the shadows. A signal. A retreat.</p>
        <p>When the dust settles, only one enemy remains. They keep him alive - not out of mercy, but purpose. There are questions to be asked, and answers to be found. Something is stirring in these lands.</p>
        <p>Even though the fight was over, it was not a time to relax. They searched for clues and information - and maybe for small treasures - as they dragged their captive toward the nearly ruined house. Inside, they found three dead travelers, clearly different from the creatures that had attacked them. Struck down, it seemed, as they passed through on their own path.</p>
        <h3>Interrogation</h3>
        <p>[ENTITY:character:Bonnie] offered to handle the interrogation. She was the only one who spoke the creature's language, and she seemed certain she could extract the answers they needed.</p>
        <p>[ENTITY:character:Olek], in his ever-merciful manner, decided to make things fair and called upon his patron to cast a [ENTITY:spell:Zone of Truth]. No lies could be spoken within its bounds. And yet, [ENTITY:character:Bonnie]'s efforts hit a wall - no amount of pain or threats, calm or enraged, made the creature utter a single word. What perhaps should have been noticed was this: [ENTITY:character:Bonnie] did not lie once, could not actually. Every horror she described, she meant.</p>
        <p>As the group debated their next step, something shifted. A glint of understanding appeared in the creature's eyes. He could understand them - and more than that, he finally spoke: <span class="dialogue">"I will answer only if the paladin promises to deliver me a swift death."</span></p>
        <p>[ENTITY:character:Olek] agreed. In exchange for three answers to three questions, he gave his word - and his word is not one given lightly.</p>
        <p>The questions were straightforward:
        <ul><li>Who is your Warlord?</li>
        <li>What are you planning here?</li>
        <li>Where are you located?</li></ul>
        <p>The answers, unfortunately, were not.</p>
        <p>The hobgoblin didn't seem to know much- and what he did know only brought more confusion than clarity. A name and a purpose were given: [ENTITY:npc:Wyrmlord Koth], a mighty sorcerer, gathering the tribes for "the Day of Ruin." A place, however, was denied. Either the creature refused to explain, or he truly didn't know how to lead them there.</p>
        <p>In the absence of a clear third answer, the group asked something else. Among the belongings of the dead, they had found a strange symbol - a sun, with a red hand painted in its center. The hobgoblin seemed to recognize it. His reaction was clear. But still, he gave them nothing more.</p>
        <p>With nothing else to say and no answers left to give, [ENTITY:character:Olek] stepped forward to fulfill his promise. But just before he struck, an idea was voiced- What if we take him to town? Maybe someone there can read his thoughts?</p>
        <p>For a heartbeat, [ENTITY:character:Olek] hesitated. A promise to his friends... a hope for more knowledge. But then he remembered the first promise - the one made in the circle of truth, under the gaze of his god.</p>
        <p>He did not break his word.</p>
        <p>Not to the hobgoblin.</p>
        <p>Not to Helm.</p>
        <p>Before continuing their way toward [ENTITY:location:Drellin's Ferry], [ENTITY:character:Bonnie] made a request: to burn the dead, to ensure they couldn't be used in any... unsavory ways. And after the flames had done their work, to extinguish the fire completely - to protect the forest and its living creatures from further harm.</p>
        <p>Starting a fire is easy. Putting one out, not so much. It took them nearly an hour, working together, dousing embers and stamping out flame. They were losing the light of day, and with it, some measure of safety in that secluded place.</p>
        <p>Once the task was done, they agreed to conceal their presence and travel quietly, slipping through trees and underbrush with as little noise as possible.</p>
        <h3>Towards Drellin's Ferry</h3>
        <p>Now, what I'm about to tell you is a brief break from the seriousness and urgency - a little moment of levity in the midst of tension. A bit of comedic relief, if you will.</p>
        <p>As they made their way through the forest, slow and steady, trying to reach the city unnoticed, [ENTITY:character:Olek] spotted something up ahead - a farmer and his two sons, walking down the road straight toward the ruined farmhouse. Toward the danger that had, just minutes ago, threatened their lives.</p>
        <p>Now, you may recall, [ENTITY:character:Olek] is not exactly inconspicuous. He's an aasimar - angelic wings, radiant features, glowing with divine presence. He doesn't quite realize how unusual he looks. So, in all sincerity, he said, "<span class="dialogue">I need to go out and warn them. The place isn't safe.</span>"</p>
        <p>For three regular folks, minding their own business in the middle of nowhere, having a giant shining celestial being suddenly emerge from the underbrush is… not exactly a routine occurrence.</p>
        <p>"<span class="dialogue">Halt,</span>" [ENTITY:character:Olek] said. "<span class="dialogue">The way you're going is not safe - </span>"</p>
        <p>He didn't even get to finish.</p>
        <p>The farmer and his sons immediately began screaming bloody murder, terrified out of their wits by the glowing figure before them. [ENTITY:character:Olek], determined to help, stepped forward, trying to calm them down.</p>
        <p>The screaming only got louder.</p>
        <p>[ENTITY:character:Olek] tried again.</p>
        <p>Still louder.</p>
        <p>And then - [ENTITY:character:Bonnie], watching this entire scene unfold with glee, decided she couldn't let the opportunity go to waste. She reached out with her magic, and whispered telepathically into the farmer's mind a single word:</p>
        <p>"<span class="dialogue">Boo.</span>"</p>
        <p>That was it. That did it.</p>
        <p>The poor family dropped everything - abandoned their cart, left their goods behind - and sprinted down the road like the Nine Hells themselves were on their heels. Caution be damned.</p>
        <p>[ENTITY:character:Olek] returned looking downcast. He was upset that he couldn't help the family, but even more so by the reaction he had gotten. He had only wanted to keep them safe- how could it have gone so wrong?</p>
        <p>What none of them noticed in the chaos was [ENTITY:character:Bonnie], who had already slipped away to the abandoned cart. Quick as ever, she grabbed the wine and stashed it safely, then returned with some food and other supplies. "<span class="dialogue">No sense letting it all go to waste,</span>" she reasoned. They did need to eat, after all. She even left behind some green vegetables, claiming it was out of kindness for the family in case they returned - though truthfully, she just didn't like those kinds.</p>
        <p>[ENTITY:character:Olek], already burdened by guilt over what had happened, refused to keep the supplies. He gathered them back into the cart, hoping the family might return for what was theirs.</p>
        <p>Everything was put back where it belonged - everything except the poorly made wine. Because as far as anyone else knew, that wine never existed in the first place.</p>
        <p>After four long and eventful days, our heroes finally reached [ENTITY:location:Drellin's Ferry].</p>
        <h3>Reaching Drellin's Ferry</h3>
        <p>The town lay mostly along the banks of a broad, sluggish river. Six old stone piers jutted from the water, marking the place where a bridge once stood - but the span itself had long since disappeared. In its place, thick ropes stretched across the river, anchored to a pair of flat-bottomed ferryboats. Brown fields and green orchards surrounded the town, and five newly built watchtowers stood tall - a curious sight for a place like this.</p>
        <p>As they moved forward, they were met by a group of armed townsfolk - three clad in leather, one in mail. </p><p>"<span class="dialogue">Halt and state your business, strangers,</span>" one of the guards called out, clearly wary of unfamiliar faces.</p>
        <p>"<span class="dialogue">We mean you no harm,</span>" [ENTITY:character:Bonnie] said, her voice light and sweet. "<span class="dialogue">We're travelers from [ENTITY:location:Brindol], here on business in town. You should know - we ran into trouble on the road. Might want to send someone to check on a farmer and his sons heading that way.</span>"</p>
        <p>She went on to describe the hobgoblin ambush and the gruesome scene they'd left behind, mentioning the poor family that had headed straight into danger.</p>
        <p>"<span class="dialogue">Ah… I'm sure they'll be fine,</span>" the guard replied - Sergeant Hersk, as he introduced himself. He told them about other recent attacks - goblins, orcs, and worse - and spoke grimly of the Witchwood, the cursed forest nearby, said to be full of unnatural things. Undead. Lost travelers. Whispers and rumors, some plausible, others wildly exaggerated.</p>
        <p>"<span class="dialogue">We understand,</span>" said one of the group. "<span class="dialogue">Now, could you point us in a few directions?</span>"</p>
        <p>They asked where they could find a place to sleep, where to locate someone named Sorana, and what other important landmarks might be worth noting.</p>
        <p>Sergeant Hersk obliged. Most activity, he said, now centered around the tollhouse. A shrine could be found in town, and a powerful wizard made his home here as well.</p>
        <p>They thanked him, and - though it's rarely a wise move - they split the party.</p>
        <p>Since everyone had business - whether out in the open or shrouded in secrets - they agreed to split up, each pursuing their own path while still united in purpose. [ENTITY:character:Olek] and [ENTITY:character:Bonnie] made their way to the tollhouse, [ENTITY:character:Norr] and [ENTITY:character:Soshi] headed for the Shrine of Pellor, and [ENTITY:character:Kaedin] set out to find the mansion of the old wizard.</p>
        <h3>Olek and Bonnie</h3>
        <p>We begin with our most unlikely pair - [ENTITY:character:Olek] and [ENTITY:character:Bonnie].</p>
        <p>They walked through the town at a steady pace, not rushed but purposeful, taking in the sights and sounds of [ENTITY:location:Drellin's Ferry]. As they moved, two small children approached them, eyes wide and hopeful, holding a tiny pouch filled with what could only be baby teeth.</p>
        <p>"<span class="dialogue">Sir, sir!</span>" one of them cried. "<span class="dialogue">We heard the tooth-fairy is in town! Do you know where to find her?</span>"</p>
        <p>Before [ENTITY:character:Olek] could answer, [ENTITY:character:Bonnie] leaned down with a warm smile. <span class="dialogue">"I'm not sure about the tooth-fairy,</span>" she said, "<span class="dialogue">but a fairy is in town.</span>" With that, she fluttered her wings and conjured a swirl of tiny, dancing illusions - glimmering fairies that sparkled in the air around them.</p>
        <p>The children squealed with delight.</p>
        <p>[ENTITY:character:Olek], not one to be outshone in kindness, summoned his floating disk and gently lifted the kids onto it, much to their giggling joy. Within moments, they were swarmed by a crowd of laughing, excited children, enchanted by the display of magic and warmth.</p>
        <p>But then, slowly pushing through the crowd, came a smaller child. His expression carried a sadness far too heavy for someone his age. He tugged gently at [ENTITY:character:Olek]'s armor.</p>
        <p>"<span class="dialogue">Sir… could you please help my mom?</span>" he asked quietly. "<span class="dialogue">My father hurts her. She's always sad, and always in pain.</span>"</p>
        <p>The weight of those words struck both [ENTITY:character:Olek] and [ENTITY:character:Bonnie] like a hammer. The laughter around them faded into the background as their focus shifted entirely.</p>
        <p>[ENTITY:character:Olek] knelt to the boy's level. "<span class="dialogue">Will you show me where you live?</span>" he asked gently.</p>
        <p>The boy nodded, and the trio set off. [ENTITY:character:Bonnie], surrounded by her squealing, sparkling parade, followed [ENTITY:character:Olek] and the child carefully - her face still light, but her mind already sharpened for what lay ahead.</p>
        <p>They arrived at a normal house, the door slightly ajar. [ENTITY:character:Olek] knocked once and gently pushed it open, while [ENTITY:character:Bonnie] waited outside with the boy and their merry group of squealing children.</p>
        <p>Inside, the boy's mother looked up, startled by the stranger stepping into her home. She appeared frail and gentle, a dark bruise already forming on her cheek.</p>
        <p>"<span class="dialogue">Who are you?</span>" she asked, concerned.</p>
        <p>[ENTITY:character:Olek] introduced himself, explaining that her child had helped him find his way here. He asked, voice full of concern, "<span class="dialogue">What happened to your face?</span>" reaching out carefully, just his fingertips brushing near the wound.</p>
        <p>The mother hesitated, her body language giving away more than she probably intended. She lied, saying she had fallen and hurt herself.</p>
        <p>[ENTITY:character:Olek] let the lie pass. Without a word, he laid his hand upon her cheek and healed her injuries - if not the ones beneath the skin, at least the ones he could reach.</p>
        <p>The woman's eyes widened in shock before softening into gratitude. She thanked him, voice trembling slightly.</p>
        <p>He tried to coax her into speaking, asking about her family, her husband, but she said little. Nothing useful. Only that her husband would return the next day.</p>
        <p>Outside, while still entertaining the other children, [ENTITY:character:Bonnie] kept a sharp ear on the conversation. Unsatisfied with how things were going, frustrated at the lack of truth, she whispered to the boy, teaching him quietly how to protect himself and his mother. Unlucky for her, just as she was about to slip him a small dagger, [ENTITY:character:Olek] emerged from the house - more perceptive than usual - and caught the whole scene before it could unfold.</p>
        <p>They said their goodbyes to the boy, promising him they would return the next day to have a word with the father.</p>
        <p>With heavier hearts than before, [ENTITY:character:Olek] and [ENTITY:character:Bonnie] made their way back into the town's bustling streets. There was still much to be done, and the day was far from over.</p>
        <p>After their brief encounter with the child and his mother, they kept the road straight to the tollhouse - no more cheery or excited with the new city.</p>
        <p>As they reached the tollhouse and stepped inside, [ENTITY:character:Bonnie], ever on the lookout, quickly noticed the state of things: about twenty guards were present, most seeming more like farmers than soldiers, with only a handful appearing slightly more experienced. This sight did not please her; it meant the city's defenses were even worse than she first feared. The room split into several corridors, each leading to different locations, and she noticed the captain's office and knocked.</p>
        <p>A tall, young woman with a stony face was deep in conversation with an older man in rich garb, a bald head, and a bushy beard.</p>
        <p>"<span class="dialogue">Hello, I am looking for Sorana</span>", said [ENTITY:character:Bonnie] as she opened the door, [ENTITY:character:Olek] right next to her.</p>
        <p>The young woman looked toward them and answered that she was Sorana, asking what she could do for them.</p>
        <p>Now, [ENTITY:character:Bonnie] hadn't shared everything with the group - for discretion, but also out of lack of trust - and so, as she presented herself and [ENTITY:character:Olek] to the two people, she spoke to Sorana mind-to-mind: <span class="dialogue"><i>I have a package for you. I was sent by Rilon Paln.</i></span></p>
        <p>Sorana responded in turn, asking to see the package.</p>
        <p>[ENTITY:character:Bonnie] handed over the envelope, inside it the leather-wrapped and strange artifact. Sorana muttered in a dreadful, evil-sounding language, and the artifact opened, revealing four items to be found - though she spoke only of the first one to [ENTITY:character:Bonnie].</p>
        <p>The item, Dead Man's Boots, was last known to be in the possession of a necromancer named Nels Huto, who had left two weeks ago toward a fortress deep inside the Witchwood, and never returned.</p>
        <p>[ENTITY:character:Bonnie] thanked Sorana, and then both she and Sorana turned their attention back to [ENTITY:character:Olek] and the bald man, who introduced himself as Norro.</p>
        <p>Norro was explaining to [ENTITY:character:Olek] the troubles the town faced - the raiders that kept attacking, how they had sent for help, and how fear was slowly creeping over their people. [ENTITY:character:Olek] told the old man about the "help" that had been sent - the three bodies they found at the farmhouse. Together with [ENTITY:character:Bonnie], they shared all the information they had gathered regarding the hobgoblins, the ambush, and the supposed warlord.</p>
        <p>To their dismay, Wormlord Koth was not the warlord - he was merely a captain. Neither Sorana nor Norro had ever heard of the "Day of Ruin" either, and could only guess that the raiders' base was somewhere deep in the Witchwood.</p>
        <p>They did, however, offer a deal: stop as many raiders as possible, and a reward would be offered to each one in their group.</p>
        <p>With the meeting concluded, and dusk starting to creep over the town, [ENTITY:character:Olek] summoned his trusty steed, lifting [ENTITY:character:Bonnie] up behind him, and together they rode toward the meeting point to reunite with the others.</p>
        <h3>Norr and Soshi</h3>
        <p>Meanwhile, not far across town, [ENTITY:character:Norr] and [ENTITY:character:Soshi] were making their own way toward the Shrine of Pelor, each carrying the weight of their own thoughts and a shared purpose.</p>
        <p>The way to the shrine took the two ladies through the city's market. The bustling streets, the yelling vendors trying to convince passersby to buy their wares, the colorful multitude of fruits, vegetables, and other foods all convinced [ENTITY:character:Norr] and [ENTITY:character:Soshi] to slow their pace and enjoy the sights.</p>
        <p>Since they were heading to a temple, an offering needed to be made - either gold, or a basket of goods. Both women were easily moved by people in unfortunate situations, especially knowing what they themselves had gone through.</p>
        <p>It was, therefore, very hard for them not to stop and listen to every merchant who pleaded their case.</p>
        <p>Soon enough, a small, old lady - frail, sweet, and sad-looking - convinced them to buy a small bundle of leafy greens for what seemed like a fair price: just five silver coins.</p>
        <p>Happy with their good deed, the two friends continued on toward a fruit stand, where a young girl greeted them with a kind and honest smile. Her price for the fruits? Also five silver coins for one kilogram - curiously enough, the very same price as the handful of greens.</p>
        <p>We could say the two girls were swindled out of their coin by a clever old woman... or we could pretend they simply did a good deed that day.</p>
        <p>With their offerings in hand and a quiet satisfaction from their small acts of kindness, [ENTITY:character:Norr] and [ENTITY:character:Soshi] made their way through the bustling streets toward the Shrine of Pelor, the weight of the city's noise fading as they neared the small yet welcoming temple.</p>
        <p>Inside the temple, two acolytes quickly approached to greet them. The women explained they wished to speak with Brother Denny and the druid Avartel. The two disciples hurried off to find them, leaving [ENTITY:character:Norr] and [ENTITY:character:Soshi] to wait. As they wandered further into the temple, they happened upon two men engaged in a deep, intense conversation.</p>
        <p>Before they could make sense of the exchange, the acolytes returned, realizing they were no longer needed. With hurried apologies, they left, and the women were left with Brother Denny.</p>
        <p>What happened next might be a bit unusual for those not familiar with shrines or temples. Brother Denny took the initiative, addressing the women with a warm but eager tone. "<span class="dialogue">How can I help you two? Did you come to make your confessions? Come now, bend your knees and tell Brother Denny what weighs on your soul.</span>"</p>
        <p>[ENTITY:character:Norr], caught completely off guard by the sudden formality, blinked and took an exaggerated step forward, half-raising herself to kneel. It was almost as if she thought she should start confessing, completely confused by the situation. But before she could do anything more absurd, [ENTITY:character:Soshi] quickly cut in, catching Brother Denny's attention. "<span class="dialogue">We brought an offering!</span>" she blurted, rescuing them from the awkwardness. The words broke Brother Denny's trance, and he finally focused on the two women.</p>
        <p>Brother Denny's enthusiasm visibly deflated when he saw that the offering was not in gold, but rather in fruits. He accepted the offering  without a second thought, and with a casual wave, he took the basket to a back room, likely for their intended use - though, one might suspect, the fruits would do little more than sustain the lifestyle of a certain priest.</p>
        <p>Left alone with the druid Avartel, the two women hesitated for a moment before shyly bringing up the reason for their visit - the lake on the map, the one that might hold a treasure. Of course, they didn't share that detail with the druid, but they did inquire about the lake itself- how to reach it, and what dangers might lie along the way.</p>
        <p>Avartel, ever kind, shared whatever information he had. He spoke of a fortress near the lake, deep within the Witchwood. The ground there was cursed, a blight that ruined everything in its path. The fortress was called Wrath Keep, and skeletons had been seen guarding the place.</p>
        <p>There was little more he could tell them; he and the other druids avoided the area whenever they could, the dangers there too great to ignore.</p>
        <p>Just as they were about to ask more, Brother Denny returned, quickly shifting the mood. He began to try and convince them to buy some of his wares. The two friends, slowly backing toward the exit, thanked both the druid and the priest before making their way to the meeting point.</p>
        <h3>Kaedin</h3>
        <p>While [ENTITY:character:Norr] and [ENTITY:character:Soshi] made their way to the shrine, [ENTITY:character:Kaedin]'s steps led him through the winding streets toward the manor on the bluffs overlooking the river. The house of Sertieren, an old noble residence with an air of mystery, stood ahead. Its crumbling grandeur seemed to whisper of forgotten secrets, the windows dark and the reputation of its haunted halls ever present. As he drew closer to the house, he couldn't help but feel the weight of its history pressing against him.</p>
        <p>[ENTITY:character:Kaedin] had seen his share of unusual things, but even he couldn't help but stop in his tracks when he stepped inside and heard the fountain speak.</p>
        <p>"<span class="dialogue">Hello there! Could I offer you some tea?</span>" said the fountain to the fighter.</p>
        <p>Frozen for a moment, [ENTITY:character:Kaedin] wasn't sure how to react, so he simply stood there, waiting for the next move.</p>
        <p>Out of nowhere, a halfling appeared - middle-aged, with spectacles perched on his nose and a mane of grey-white hair. He echoed the fountain's question, his voice warm and casual, as if this were a perfectly normal occurrence.</p>
        <p>[ENTITY:character:Kaedin] blinked, gathering his bearings. He quickly deduced that the mansion was infused with magic, no doubt from the wizard Sertieren himself. Of course the fountain could speak. With a steady breath, [ENTITY:character:Kaedin] finally spoke up, his mind shifting gears. "<span class="dialogue">Perhaps something stronger? Do you have any spirits?</span>"</p>
        <p>The halfling's eyes lit up with delight, and he scurried to a worktable nearby, seemingly pleased by the request. In no time, he returned with a glass of what could only loosely be described as rum - or something very close to it.</p>
        <p>[ENTITY:character:Kaedin] began explaining why he had sought out the wizard, asking questions about mysterious magic, strange disappearances - anything that could offer a hint for his quest to find Talos and bring him home.</p>
        <p>Sertieren, delighted to have a visitor to talk to, started rambling: he spoke of odd vanishings, though it was unclear if they were true or just the work of charlatans playing tricks. He muttered about the Chronomancers of [ENTITY:guild:Krynn], how nine people had once gone to investigate them and nine had been killed by dragons - or so the rumors said. He mentioned a magical site, a nexus of some kind where these events were said to happen, though he couldn't say exactly where - probably somewhere deep within the Witchwood.</p>
        <p>Before long, Sertieren drifted into complaining about how people had called him mad, paranoid, whenever he urged them to strengthen the city's defenses... and now, he said with a grim satisfaction, danger had come to [ENTITY:location:Drellin's Ferry] again.</p>
        <p>[ENTITY:character:Kaedin] listened quietly, filing away the important pieces of information in his mind, slowly sipping the rum Sertieren had provided.</p>
        <p>At last, realizing Sertieren had no more real answers - only half-truths and rumors - [ENTITY:character:Kaedin] drained the last of his drink and took his leave with a brief, tight nod. The manor's heavy door creaked shut behind him, and he stood for a moment at the edge of the bluffs, the wind off the river cold against his face. Somewhere out there, Talos was still missing.</p>
        <p>Setting his jaw, [ENTITY:character:Kaedin] pulled his cloak tighter and turned back toward the town, each step measured, purposeful, as he made his way to the meeting point to rejoin the others. </p>        
        `,
		recap: `<p>Our weary heroes journey toward [ENTITY:location:Drellin's Ferry] on their fourth day of travel through the monotonous lands of Elsir Vale. As they crest a low rise, they discover an abandoned farmhouse in a dusty grove—the perfect setting for an ambush, as [ENTITY:character:Bonnie] shrewdly notes. Her instincts prove correct when hobgoblins attack from the brush.</p>
        <p>The ensuing battle is fierce, but our heroes display remarkable teamwork: [ENTITY:character:Norr]'s lightning combining with [ENTITY:character:Soshi]'s flames, [ENTITY:character:Kaedin]'s echo striking in tandem with [ENTITY:character:Olek]'s glowing club, and [ENTITY:character:Bonnie] delivering the final blow with precise dagger work. When the dust settles, they capture one hobgoblin alive for questioning.</p>

        <p>Inside the farmhouse, they discover three murdered travelers. Despite [ENTITY:character:Bonnie]'s interrogation skills and [ENTITY:character:Olek]'s [ENTITY:spell:Zone of Truth], the creature remains silent until he finally bargains: answers in exchange for a swift death from the paladin. He reveals his leader is [ENTITY:npc:Wyrmlord Koth], a sorcerer gathering tribes for "the Day of Ruin," but refuses to disclose their location. After fulfilling his promise to the hobgoblin, [ENTITY:character:Olek] and the party burn the dead to prevent necromantic misuse.</p>

        <p>As they travel stealthily toward town, [ENTITY:character:Olek] spots a farmer and his sons heading toward danger. In his well-meaning attempt to warn them, the glowing aasimar terrifies the family, who flee screaming—a situation [ENTITY:character:Bonnie] worsens by whispering "Boo" telepathically into the farmer's mind. [ENTITY:character:Olek], distressed by their reaction, insists on returning their abandoned supplies—though mysteriously, the cart's wine vanishes before it's restored.</p>

        <p>Finally reaching [ENTITY:location:Drellin's Ferry], our heroes are greeted by town guards who inform them of increased raids in the area. The party splits to pursue individual goals: [ENTITY:character:Olek] and [ENTITY:character:Bonnie] heading to the tollhouse, [ENTITY:character:Norr] and [ENTITY:character:Soshi] to the Shrine of Pelor, and [ENTITY:character:Kaedin] to find the wizard's mansion.</p>

        <p>[ENTITY:character:Olek] and [ENTITY:character:Bonnie]'s journey takes an unexpected turn when children approach them seeking the tooth-fairy. Amidst the magical entertainment they provide, a small boy asks for help with his abusive father. They visit his home where [ENTITY:character:Olek] heals the mother's visible injuries, though she denies any abuse. Outside, [ENTITY:character:Bonnie] attempts to slip the boy a dagger before [ENTITY:character:Olek] intervenes, and they promise to return the next day.</p>

        <p>At the tollhouse, [ENTITY:character:Bonnie] meets Sorana to deliver a package containing magical artifacts, learning that the "Dead Man's Boots" were last possessed by a necromancer who disappeared in the Witchwood. Meanwhile, town leader Norro explains their troubles with raiders and offers rewards for stopping them.</p>

        <p>Elsewhere, [ENTITY:character:Norr] and [ENTITY:character:Soshi] purchase offerings at the market before visiting the Shrine of Pelor. There, Brother Denny awkwardly attempts to hear their confessions, while the druid Avartel shares information about a cursed fortress called Wrath Keep near a lake in the Witchwood, guarded by skeletons.</p>

        <p>Finally, [ENTITY:character:Kaedin] visits Sertieren's manor, where he's greeted by a talking fountain and the eccentric wizard himself. Over questionable rum, Sertieren rambles about odd vanishings, the Chronomancers of [ENTITY:guild:Krynn], and a magical nexus somewhere in the Witchwood. Though mostly offering rumors rather than concrete information about Talos's disappearance, [ENTITY:character:Kaedin] departs with new leads to pursue.</p>

        <p>As dusk falls over [ENTITY:location:Drellin's Ferry], our separated heroes make their way to reunite, each carrying pieces of a mystery that seems to center on the ominous Witchwood and the threats gathering within it.</p>`,
	},
];
