const CAMPAIGN_002_METADATA = {
	BONNIE: {
		abilityScores: [
			{ name: 'Strength', abbr: 'str', score: '-1', value: '8' },
			{ name: 'Dexterity', abbr: 'dex', score: '+4', value: '19' },
			{ name: 'Constitution', abbr: 'con', score: '+2', value: '14' },
			{ name: 'Intelligence', abbr: 'int', score: '+2', value: '14' },
			{ name: 'Wisdom', abbr: 'wis', score: '+0', value: '10' },
			{ name: 'Charisma', abbr: 'cha', score: '+1', value: '12' },
		],
		savingThrows: [
			{ name: 'str', value: '-1' },
			{ name: 'dex', value: '+7' },
			{ name: 'con', value: '+2' },
			{ name: 'int', value: '+5' },
			{ name: 'wis', value: '+0' },
			{ name: 'cha', value: '+1' },
		],
		spellData: [
			{
				groupName: 'Cantrip',
				spells: [
					{
						spellInfo: { spellName: 'Druidcraft', spellMetaInfo: 'Fairy Magic' },
						range: '30ft.',
						slotType: '1A',
						effect: 'Utility',
					},
					{
						spellInfo: { spellName: 'Green-Flame Blade', spellMetaInfo: 'Rogue' },
						range: 'Self',
						slotType: '1A',
						effect: '1d8*',
					},
					{
						spellInfo: { spellName: 'Mage Hand', spellMetaInfo: 'Mage Hand Legerdemain' },
						range: '30ft.',
						slotType: '1BA',
						effect: 'Utility',
					},
					{
						spellInfo: { spellName: 'Message', spellMetaInfo: 'Rogue' },
						range: '120ft.',
						slotType: '1A',
						effect: 'Communication*',
					},
				],
			},
			{
				groupName: '1st Level',
				spells: [
					{
						spellInfo: { spellName: 'Absorb Elements', spellMetaInfo: 'Rogue' },
						range: 'Self',
						slotType: '1R',
						effect: '1d6*',
					},
					{
						spellInfo: { spellName: 'Comprehend Languages', spellMetaInfo: 'Rogue' },
						range: 'Self',
						slotType: '1A',
						effect: 'Social',
					},
					{
						spellInfo: { spellName: 'Faerie Fire', spellMetaInfo: 'Fairy Magic' },
						range: '60ft.',
						slotType: '1A',
						effect: 'Invisible',
					},
					{
						spellInfo: { spellName: 'Find Familiar', spellMetaInfo: 'Rogue' },
						range: '10ft.',
						slotType: '1h',
						effect: 'Summoning',
					},
					{
						spellInfo: { spellName: 'Shield', spellMetaInfo: 'Rogue' },
						range: 'Self',
						slotType: '1R',
						effect: 'Warding',
					},
				],
			},
			{
				groupName: '2nd Level',
				spells: [
					{
						spellInfo: { spellName: 'Enlarge/Reduce', spellMetaInfo: 'Fairy Magic' },
						range: '30ft.',
						slotType: '1A',
						effect: 'Buff',
					},
				],
			},
		],
		actionData: [
			'Invisibility ',
			'Nick (Dagger) ',
			'Sneak Attack ',
			'Sneak Attack: Poison (Cost: 1d6) ',
			'Sneak Attack: Trip (Cost: 1d6) ',
			'Sneak Attack: Withdraw (Cost: 1d6) ',
			'Unarmed Strike ',
			'Vex (Shortsword) ',
			'Cunning Action ',
			'Steady Aim ',
			'Uncanny Dodge ',
		],
		features: [
			'Core Rogue Traits',
			'Expertise',
			'Sneak Attack',
			'Thieves’ Cant',
			'Weapon Mastery',
			'Cunning Action',
			'Rogue Subclass',
			'Steady Aim',
			'Spellcasting',
			'Mage Hand Legerdemain',
			'Ability Score Improvement',
			'Cunning Strike',
			'Uncanny Dodge',
			'6: Expertise',
			'Fairy Magic',
			'Hidden Tricksters.',
			'Ability Score Improvement',
		],
		healthPoints: '41',
		armorClass: '16',
		walkingSpeed: '30ft.',
	},
	KAEDIN: {
		abilityScores: [
			{ name: 'Strength', abbr: 'str', score: '+4', value: '18' },
			{ name: 'Dexterity', abbr: 'dex', score: '+1', value: '12' },
			{ name: 'Constitution', abbr: 'con', score: '+3', value: '16' },
			{ name: 'Intelligence', abbr: 'int', score: '+0', value: '10' },
			{ name: 'Wisdom', abbr: 'wis', score: '+1', value: '13' },
			{ name: 'Charisma', abbr: 'cha', score: '-1', value: '8' },
		],
		savingThrows: [
			{ name: 'str', value: '+7' },
			{ name: 'dex', value: '+1' },
			{ name: 'con', value: '+6' },
			{ name: 'int', value: '+0' },
			{ name: 'wis', value: '+1' },
			{ name: 'cha', value: '-1' },
		],
		spellData: [
			{
				groupName: '2nd Level',
				spells: [
					{
						spellInfo: { spellName: 'Pass without Trace', spellMetaInfo: 'Legacy | Merge with Stone' },
						range: 'Self',
						slotType: '1A',
						effect: 'Buff*',
					},
				],
			},
		],
		actionData: [
			'Cleave (Greataxe) ',
			'Cleave (Halberd) ',
			'Graze (Glaive) ',
			'Graze (Greatsword) ',
			'Heavy Weapon Mastery ',
			'Unarmed Strike ',
			'Hew ',
			'Manifest Echo ',
			'Manifest Echo: Step ',
			'Second Wind ',
			'Second Wind: Tactical Shift ',
			'Manifest Echo: React ',
			'Action Surge (Special)',
			'Manifest Echo: Command (Special)',
			'Manifest Echo: Strike (Special)',
			'Tactical Mind (Special)',
			'Unleash Incarnation (Special)',
		],
		features: [
			'Core Fighter Traits',
			'Fighting Style',
			'Second Wind',
			'Weapon Mastery',
			'Action Surge',
			'Tactical Mind',
			'Fighter Subclass',
			'Manifest Echo',
			'Unleash Incarnation',
			'4: Weapon Mastery',
			'Ability Score Improvement',
			'Extra Attack',
			'Tactical Shift',
			'6: Ability Score Improvement',
			'Earth Walk',
			'Merge with Stone',
			'Great Weapon Fighting',
			'Sentinel',
			'Great Weapon Master',
			'Savage Attacker',
		],
		healthPoints: '58',
		armorClass: '16',
		walkingSpeed: '30ft.',
	},
	SOSHI: {
		abilityScores: [
			{ name: 'Strength', abbr: 'str', score: '-1', value: '8' },
			{ name: 'Dexterity', abbr: 'dex', score: '+2', value: '15' },
			{ name: 'Constitution', abbr: 'con', score: '+3', value: '16' },
			{ name: 'Intelligence', abbr: 'int', score: '+2', value: '15' },
			{ name: 'Wisdom', abbr: 'wis', score: '+1', value: '12' },
			{ name: 'Charisma', abbr: 'cha', score: '+0', value: '10' },
		],
		savingThrows: [
			{ name: 'str', value: '-1' },
			{ name: 'dex', value: '+2' },
			{ name: 'con', value: '+6' },
			{ name: 'int', value: '+5' },
			{ name: 'wis', value: '+4' },
			{ name: 'cha', value: '+0' },
		],
		spellData: [
			{
				groupName: 'Cantrip',
				spells: [
					{
						spellInfo: { spellName: 'Acid Splash', spellMetaInfo: 'Wizard' },
						range: '60ft.',
						slotType: '1A',
						effect: '2d6',
					},
					{
						spellInfo: { spellName: 'Booming Blade', spellMetaInfo: 'Wizard' },
						range: 'Self',
						slotType: '1A',
						effect: '1d8*',
					},
					{
						spellInfo: { spellName: 'Chill Touch', spellMetaInfo: 'Wizard' },
						range: 'Touch',
						slotType: '1A',
						effect: '2d10',
					},
					{
						spellInfo: { spellName: 'Elementalism', spellMetaInfo: 'Magic Initiate (Wizard)' },
						range: '30ft.',
						slotType: '1A',
						effect: '',
					},
					{
						spellInfo: { spellName: 'Fire Bolt', spellMetaInfo: 'Evocation Savant' },
						range: '120ft.',
						slotType: '1A',
						effect: '2d10',
					},
					{
						spellInfo: { spellName: 'Poison Spray', spellMetaInfo: 'Magic Initiate (Wizard)' },
						range: '30ft.',
						slotType: '1A',
						effect: '2d12',
					},
					{
						spellInfo: { spellName: 'Ray of Frost', spellMetaInfo: 'Wizard' },
						range: '60ft.',
						slotType: '1A',
						effect: '2d8',
					},
				],
			},
			{
				groupName: '1st Level',
				spells: [
					{
						spellInfo: { spellName: 'Absorb Elements', spellMetaInfo: 'Wizard' },
						range: 'Self',
						slotType: '1R',
						effect: '1d6*',
					},
					{
						spellInfo: { spellName: 'Fog Cloud', spellMetaInfo: 'Wizard' },
						range: '120ft.',
						slotType: '1A',
						effect: 'Control*',
					},
					{
						spellInfo: { spellName: 'Mage Armor', spellMetaInfo: 'Wizard' },
						range: 'Touch',
						slotType: '1A',
						effect: 'Buff*',
					},
					{
						spellInfo: { spellName: 'Mage Armor', spellMetaInfo: 'Magic Initiate (Wizard)' },
						range: 'Touch',
						slotType: '1A',
						effect: 'Buff*',
					},
					{
						spellInfo: { spellName: 'Shield', spellMetaInfo: 'Wizard' },
						range: 'Self',
						slotType: '1R',
						effect: 'Warding',
					},
				],
			},
			{
				groupName: '2nd Level',
				spells: [
					{
						spellInfo: { spellName: 'Absorb Elements', spellMetaInfo: 'Wizard' },
						range: 'Self',
						slotType: '1R',
						effect: '2d6*',
					},
					{
						spellInfo: { spellName: 'Fog Cloud', spellMetaInfo: 'Wizard' },
						range: '120ft.',
						slotType: '1A',
						effect: 'Control*',
					},
					{
						spellInfo: { spellName: 'Mirror Image', spellMetaInfo: 'Wizard' },
						range: 'Self',
						slotType: '1A',
						effect: 'Deception*',
					},
					{
						spellInfo: { spellName: 'Misty Step', spellMetaInfo: 'Legacy | Fey Step' },
						range: 'Self',
						slotType: '1BA',
						effect: 'Teleportation',
					},
					{
						spellInfo: { spellName: 'Scorching Ray', spellMetaInfo: 'Evocation Savant' },
						range: '120ft.',
						slotType: '1A',
						effect: '2d6',
					},
				],
			},
			{
				groupName: '3rd Level',
				spells: [
					{
						spellInfo: { spellName: 'Absorb Elements', spellMetaInfo: 'Wizard' },
						range: 'Self',
						slotType: '1R',
						effect: '3d6*',
					},
					{
						spellInfo: { spellName: 'Blink', spellMetaInfo: 'Wizard' },
						range: 'Self',
						slotType: '1A',
						effect: 'Utility',
					},
					{
						spellInfo: { spellName: 'Dispel Magic', spellMetaInfo: 'Wizard' },
						range: '120ft.',
						slotType: '1A',
						effect: 'Control',
					},
					{
						spellInfo: { spellName: 'Fireball', spellMetaInfo: 'Wizard' },
						range: '150ft.',
						slotType: '1A',
						effect: '8d6',
					},
					{
						spellInfo: { spellName: 'Fly', spellMetaInfo: 'Wizard' },
						range: 'Touch',
						slotType: '1A',
						effect: 'Movement',
					},
					{
						spellInfo: { spellName: 'Fog Cloud', spellMetaInfo: 'Wizard' },
						range: '120ft.',
						slotType: '1A',
						effect: 'Control*',
					},
					{
						spellInfo: { spellName: 'Lightning Bolt', spellMetaInfo: 'Wizard' },
						range: 'Self',
						slotType: '1A',
						effect: '8d6',
					},
					{
						spellInfo: { spellName: 'Scorching Ray', spellMetaInfo: 'Evocation Savant' },
						range: '120ft.',
						slotType: '1A',
						effect: '2d6',
					},
				],
			},
		],
		actionData: [
			'Unarmed Strike ',
			'Arcane Recovery (Special)',
			'Elemental Acuity Stacks (No Action)',
			'Sculpt Spells (Special)',
		],
		features: [
			'Core Wizard Traits',
			'Spellcasting',
			'Ritual Adept',
			'Arcane Recovery',
			'Scholar',
			'Wizard Subclass',
			'Evocation Savant',
			'Potent Cantrip',
			'Ability Score Improvement',
			'Memorize Spell',
			'Sculpt Spells',
			'Darkvision',
			'Keen Senses',
			'Fey Ancestry',
			'Trance',
			'Elf Weapon Training',
			'Fey Step',
			'Resilient',
			'Magic Initiate (Wizard)',
			'Elemental Acuity Reservoir',
		],
		healthPoints: '44',
		armorClass: '12',
		walkingSpeed: '30ft.',
	},
	NORR: {
		abilityScores: [
			{ name: 'Strength', abbr: 'str', score: '-1', value: '8' },
			{ name: 'Dexterity', abbr: 'dex', score: '+2', value: '14' },
			{ name: 'Constitution', abbr: 'con', score: '+2', value: '14' },
			{ name: 'Intelligence', abbr: 'int', score: '+0', value: '10' },
			{ name: 'Wisdom', abbr: 'wis', score: '+1', value: '12' },
			{ name: 'Charisma', abbr: 'cha', score: '+4', value: '18' },
		],
		savingThrows: [
			{ name: 'str', value: '-1' },
			{ name: 'dex', value: '+2' },
			{ name: 'con', value: '+5' },
			{ name: 'int', value: '+0' },
			{ name: 'wis', value: '+1' },
			{ name: 'cha', value: '+7' },
		],
		spellData: [
			{
				groupName: 'Cantrip',
				spells: [
					{
						spellInfo: { spellName: 'Fire Bolt', spellMetaInfo: 'Sorcerer' },
						range: '120ft.',
						slotType: '1A',
						effect: '2d10',
					},
					{
						spellInfo: { spellName: 'Guidance', spellMetaInfo: 'Magic Initiate (Cleric)' },
						range: 'Touch',
						slotType: '1A',
						effect: 'Buff',
					},
					{
						spellInfo: { spellName: 'Light', spellMetaInfo: 'Magic Initiate (Cleric)' },
						range: 'Touch',
						slotType: '1A',
						effect: 'Creation*',
					},
					{
						spellInfo: { spellName: 'Mending', spellMetaInfo: 'Sorcerer' },
						range: 'Touch',
						slotType: '1m',
						effect: 'Utility',
					},
					{
						spellInfo: { spellName: 'Message', spellMetaInfo: 'Sorcerer' },
						range: '120ft.',
						slotType: '1A',
						effect: 'Communication*',
					},
					{
						spellInfo: { spellName: 'Sorcerous Burst', spellMetaInfo: 'Sorcerer' },
						range: '120ft.',
						slotType: '1A',
						effect: '2d8*',
					},
				],
			},
			{
				groupName: '1st Level',
				spells: [
					{
						spellInfo: { spellName: 'Chromatic Orb', spellMetaInfo: 'Draconic Spells' },
						range: '90ft.',
						slotType: '1A',
						effect: '3d8*',
					},
					{
						spellInfo: { spellName: 'Command', spellMetaInfo: 'Draconic Spells' },
						range: '60ft.',
						slotType: '1A',
						effect: 'Prone',
					},
					{
						spellInfo: { spellName: 'Create or Destroy Water', spellMetaInfo: 'Magic Initiate (Cleric)' },
						range: '30ft.',
						slotType: '1A',
						effect: 'Creation',
					},
					{
						spellInfo: { spellName: 'Detect Magic', spellMetaInfo: 'Sorcerer' },
						range: 'Self',
						slotType: '1A',
						effect: 'Detection',
					},
					{
						spellInfo: { spellName: 'Shield', spellMetaInfo: 'Sorcerer' },
						range: 'Self',
						slotType: '1R',
						effect: 'Warding',
					},
				],
			},
			{
				groupName: '2nd Level',
				spells: [
					{
						spellInfo: { spellName: 'Alter Self', spellMetaInfo: 'Draconic Spells' },
						range: 'Self',
						slotType: '1A',
						effect: 'Shapechanging',
					},
					{
						spellInfo: { spellName: 'Chromatic Orb', spellMetaInfo: 'Draconic Spells' },
						range: '90ft.',
						slotType: '1A',
						effect: '4d8*',
					},
					{
						spellInfo: { spellName: 'Command', spellMetaInfo: 'Draconic Spells' },
						range: '60ft.',
						slotType: '1A',
						effect: 'Prone',
					},
					{
						spellInfo: { spellName: "Dragon's Breath", spellMetaInfo: 'Draconic Spells' },
						range: 'Touch',
						slotType: '1BA',
						effect: '3d6*',
					},
					{
						spellInfo: { spellName: 'Enhance Ability', spellMetaInfo: 'Sorcerer' },
						range: 'Touch',
						slotType: '1A',
						effect: 'Buff',
					},
					{
						spellInfo: { spellName: 'Magic Weapon', spellMetaInfo: 'Sorcerer' },
						range: 'Touch',
						slotType: '1BA',
						effect: 'Buff',
					},
					{
						spellInfo: { spellName: 'Misty Step', spellMetaInfo: 'Sorcerer' },
						range: 'Self',
						slotType: '1BA',
						effect: 'Teleportation',
					},
				],
			},
			{
				groupName: '3rd Level',
				spells: [
					{
						spellInfo: { spellName: 'Alter Self', spellMetaInfo: 'Draconic Spells' },
						range: 'Self',
						slotType: '1A',
						effect: 'Shapechanging',
					},
					{
						spellInfo: { spellName: 'Blink', spellMetaInfo: 'Sorcerer' },
						range: 'Self',
						slotType: '1A',
						effect: 'Utility',
					},
					{
						spellInfo: { spellName: 'Chromatic Orb', spellMetaInfo: 'Draconic Spells' },
						range: '90ft.',
						slotType: '1A',
						effect: '5d8*',
					},
					{
						spellInfo: { spellName: 'Command', spellMetaInfo: 'Draconic Spells' },
						range: '60ft.',
						slotType: '1A',
						effect: 'Prone',
					},
					{
						spellInfo: { spellName: 'Counterspell', spellMetaInfo: 'Sorcerer' },
						range: '60ft.',
						slotType: '1R',
						effect: 'Negation',
					},
					{
						spellInfo: { spellName: "Dragon's Breath", spellMetaInfo: 'Draconic Spells' },
						range: 'Touch',
						slotType: '1BA',
						effect: '4d6*',
					},
					{
						spellInfo: { spellName: 'Enhance Ability', spellMetaInfo: 'Sorcerer' },
						range: 'Touch',
						slotType: '1A',
						effect: 'Buff',
					},
					{
						spellInfo: { spellName: 'Fear', spellMetaInfo: 'Draconic Spells' },
						range: 'Self',
						slotType: '1A',
						effect: 'Frightened*',
					},
					{
						spellInfo: { spellName: 'Fly', spellMetaInfo: 'Draconic Spells' },
						range: 'Touch',
						slotType: '1A',
						effect: 'Movement',
					},
					{
						spellInfo: { spellName: 'Haste', spellMetaInfo: 'Sorcerer' },
						range: '30ft.',
						slotType: '1A',
						effect: 'Buff',
					},
					{
						spellInfo: { spellName: 'Lightning Bolt', spellMetaInfo: 'Sorcerer' },
						range: 'Self',
						slotType: '1A',
						effect: '8d6',
					},
					{
						spellInfo: { spellName: 'Magic Weapon', spellMetaInfo: 'Sorcerer' },
						range: 'Touch',
						slotType: '1BA',
						effect: 'Buff',
					},
					{
						spellInfo: { spellName: 'Slow', spellMetaInfo: 'Sorcerer' },
						range: '120ft.',
						slotType: '1A',
						effect: 'Control*',
					},
				],
			},
		],
		actionData: [
			'Unarmed Strike ',
			'Font of Magic: Create Spell Slot Level 1 ',
			'Font of Magic: Create Spell Slot Level 2 ',
			'Font of Magic: Create Spell Slot Level 3 ',
			'Innate Sorcery ',
			'Font of Magic: Convert Spell Slots (No Action)',
			'Font of Magic: Sorcery Points (Special)',
			'Metamagic: Empowered Spell (Special)',
			'Metamagic: Quickened Spell (Special)',
			'Sorcerous Restoration (Special)',
		],
		features: [
			'Core Sorcerer Traits',
			'Spellcasting',
			'Innate Sorcery',
			'Font of Magic',
			'Metamagic',
			'Metamagic Options',
			'Sorcerer Subclass',
			'Draconic Resilience',
			'Draconic Spells',
			'Ability Score Improvement',
			'Sorcerous Restoration',
			'Elemental Affinity',
			'Creature Type',
			'Size',
			'Speed',
			'Resourceful',
			'Skillful',
			'Versatile',
			'Ability Score Increases',
			'Elemental Adept',
			'Magic Initiate (Cleric)',
			'Tough',
		],
		healthPoints: '56',
		armorClass: '16',
		walkingSpeed: '30ft.',
	},
	OLEK: {
		abilityScores: [
			{ name: 'Strength', abbr: 'str', score: '+2', value: '14' },
			{ name: 'Dexterity', abbr: 'dex', score: '-1', value: '8' },
			{ name: 'Constitution', abbr: 'con', score: '+2', value: '14' },
			{ name: 'Intelligence', abbr: 'int', score: '+0', value: '10' },
			{ name: 'Wisdom', abbr: 'wis', score: '+1', value: '12' },
			{ name: 'Charisma', abbr: 'cha', score: '+4', value: '18' },
		],
		savingThrows: [
			{ name: 'str', value: '+2' },
			{ name: 'dex', value: '-1' },
			{ name: 'con', value: '+2' },
			{ name: 'int', value: '+0' },
			{ name: 'wis', value: '+4' },
			{ name: 'cha', value: '+7' },
		],
		spellData: [
			{
				groupName: 'Cantrip',
				spells: [
					{
						spellInfo: { spellName: 'Booming Blade', spellMetaInfo: 'Warlock' },
						range: 'Self',
						slotType: '1A',
						effect: '1d8*',
					},
					{
						spellInfo: { spellName: 'Guidance', spellMetaInfo: 'Eldritch Invocations' },
						range: 'Touch',
						slotType: '1A',
						effect: 'Buff',
					},
					{
						spellInfo: { spellName: 'Light', spellMetaInfo: 'Light Bearer' },
						range: 'Touch',
						slotType: '1A',
						effect: 'Creation*',
					},
					{
						spellInfo: { spellName: 'Mage Hand', spellMetaInfo: 'Warlock' },
						range: '30ft.',
						slotType: '1A',
						effect: 'Utility',
					},
					{
						spellInfo: { spellName: 'Message', spellMetaInfo: 'Eldritch Invocations' },
						range: '120ft.',
						slotType: '1A',
						effect: 'Communication*',
					},
					{
						spellInfo: { spellName: 'Shillelagh*', spellMetaInfo: 'Eldritch Invocations' },
						range: 'Self',
						slotType: '1BA',
						effect: '1d10+6*',
					},
				],
			},
			{
				groupName: '1st Level',
				spells: [
					{
						spellInfo: { spellName: 'Bless', spellMetaInfo: 'Paladin' },
						range: '30ft.',
						slotType: '1A',
						effect: 'Buff',
					},
					{
						spellInfo: { spellName: 'Cure Wounds', spellMetaInfo: 'Paladin' },
						range: 'Touch',
						slotType: '1A',
						effect: '2d8+4 ',
					},
					{
						spellInfo: { spellName: 'Detect Magic', spellMetaInfo: 'Eldritch Invocations' },
						range: 'Self',
						slotType: '1A',
						effect: 'Detection',
					},
					{
						spellInfo: { spellName: 'Divine Smite', spellMetaInfo: 'Paladin’s Smite' },
						range: 'Self',
						slotType: '1BA',
						effect: '2d8',
					},
					{
						spellInfo: { spellName: 'Divine Smite', spellMetaInfo: 'Paladin’s Smite' },
						range: 'Self',
						slotType: '1BA',
						effect: '2d8',
					},
					{
						spellInfo: { spellName: 'Protection from Evil and Good', spellMetaInfo: 'Oath of Devotion Spells' },
						range: 'Touch',
						slotType: '1A',
						effect: 'Buff*',
					},
					{
						spellInfo: { spellName: 'Searing Smite', spellMetaInfo: 'Paladin' },
						range: 'Self',
						slotType: '1BA',
						effect: '1d6*',
					},
					{
						spellInfo: { spellName: 'Shield of Faith', spellMetaInfo: 'Oath of Devotion Spells' },
						range: '60ft.',
						slotType: '1BA',
						effect: 'Buff*',
					},
					{
						spellInfo: { spellName: 'Speak with Animals', spellMetaInfo: 'Warlock' },
						range: 'Self',
						slotType: '1A',
						effect: 'Communication*',
					},
					{
						spellInfo: { spellName: "Tasha's Hideous Laughter", spellMetaInfo: 'Warlock' },
						range: '30ft.',
						slotType: '1A',
						effect: 'Prone*',
					},
					{
						spellInfo: { spellName: "Tenser's Floating Disk", spellMetaInfo: 'Eldritch Invocations' },
						range: '30ft.',
						slotType: '1A',
						effect: 'Movement*',
					},
				],
			},
			{
				groupName: '2nd Level',
				spells: [
					{
						spellInfo: { spellName: 'Aid', spellMetaInfo: 'Oath of Devotion Spells' },
						range: '30ft.',
						slotType: '1A',
						effect: '5 ',
					},
					{
						spellInfo: { spellName: 'Bless', spellMetaInfo: 'Paladin' },
						range: '30ft.',
						slotType: '1A',
						effect: 'Buff',
					},
					{
						spellInfo: { spellName: 'Cure Wounds', spellMetaInfo: 'Paladin' },
						range: 'Touch',
						slotType: '1A',
						effect: '4d8+4 ',
					},
					{
						spellInfo: { spellName: 'Detect Magic', spellMetaInfo: 'Eldritch Invocations' },
						range: 'Self',
						slotType: '1A',
						effect: 'Detection',
					},
					{
						spellInfo: { spellName: 'Divine Smite', spellMetaInfo: 'Paladin’s Smite' },
						range: 'Self',
						slotType: '1BA',
						effect: '3d8',
					},
					{
						spellInfo: { spellName: 'Find Steed', spellMetaInfo: 'Faithful Steed' },
						range: '30ft.',
						slotType: '1A',
						effect: 'Summoning',
					},
					{
						spellInfo: { spellName: 'Find Steed', spellMetaInfo: 'Faithful Steed' },
						range: '30ft.',
						slotType: '1A',
						effect: 'Summoning',
					},
					{
						spellInfo: { spellName: 'Locate Object', spellMetaInfo: 'Paladin' },
						range: 'Self',
						slotType: '1A',
						effect: 'Detection',
					},
					{
						spellInfo: { spellName: 'Magic Weapon', spellMetaInfo: 'Paladin' },
						range: 'Touch',
						slotType: '1BA',
						effect: 'Buff',
					},
					{
						spellInfo: { spellName: 'Protection from Evil and Good', spellMetaInfo: 'Oath of Devotion Spells' },
						range: 'Touch',
						slotType: '1A',
						effect: 'Buff*',
					},
					{
						spellInfo: { spellName: 'Searing Smite', spellMetaInfo: 'Paladin' },
						range: 'Self',
						slotType: '1BA',
						effect: '2d6*',
					},
					{
						spellInfo: { spellName: 'Shield of Faith', spellMetaInfo: 'Oath of Devotion Spells' },
						range: '60ft.',
						slotType: '1BA',
						effect: 'Buff*',
					},
					{
						spellInfo: { spellName: 'Shining Smite', spellMetaInfo: 'Paladin' },
						range: 'Self',
						slotType: '1BA',
						effect: '2d6',
					},
					{
						spellInfo: { spellName: "Tasha's Hideous Laughter", spellMetaInfo: 'Warlock' },
						range: '30ft.',
						slotType: '1A',
						effect: 'Prone*',
					},
					{
						spellInfo: { spellName: "Tenser's Floating Disk", spellMetaInfo: 'Eldritch Invocations' },
						range: '30ft.',
						slotType: '1A',
						effect: 'Movement*',
					},
					{
						spellInfo: { spellName: 'Zone of Truth', spellMetaInfo: 'Oath of Devotion Spells' },
						range: '60ft.',
						slotType: '1A',
						effect: 'Control',
					},
				],
			},
		],
		actionData: [
			'Channel Divinity ',
			'Cleave (Greataxe) ',
			'Healing Hands ',
			'Sacred Weapon: Imbue Weapon ',
			'Topple (Quarterstaff) ',
			'Unarmed Strike ',
			'Celestial Revelation ',
			'Channel Divinity: Divine Sense ',
			'Lay On Hands: Heal ',
			'Lay On Hands: Healing Pool ',
			'Lay On Hands: Purify Poison ',
			'Reactive Spell ',
		],
		features: [
			'Core Paladin Traits',
			'Lay On Hands',
			'Spellcasting',
			'Weapon Mastery',
			'Fighting Style',
			'Paladin’s Smite',
			'Channel Divinity',
			'Paladin Subclass',
			'Oath of Devotion Spells',
			'Sacred Weapon',
			'Ability Score Improvement',
			'Extra Attack',
			'Faithful Steed',
			'Core Warlock Traits',
			'Eldritch Invocations',
			'Pact Magic',
			'Creature Type',
			'Size',
			'Speed',
			'Celestial Resistance',
			'Darkvision',
			'Healing Hands',
			'Light Bearer',
			'Celestial Revelation',
			'Ability Score Increases',
			'War Caster',
			'Alert',
			'Dueling',
		],
		healthPoints: '51',
		armorClass: '18',
		walkingSpeed: '30ft.',
	},
};
