const CAMPAIGN_02_CHARACTERS = [
	{
		name: 'Bonnie',
		race: 'Pixie',
		class: 'Rogue',
		level: 6,
		icon: 'images/assets/character_thumbnails/campaign_002/bonnie.jpeg',
		background: CAMPAIGN_02_BACKGROUNDS.BONNIE.background,
		shortDescription: CAMPAIGN_02_BACKGROUNDS.BONNIE.shortDescription,
	},
	{
		name: 'Kaedin',
		race: 'Earth Genasi',
		class: 'Echo Knight',
		level: 6,
		icon: 'images/assets/character_thumbnails/campaign_002/kaedin.jpeg',
		background: CAMPAIGN_02_BACKGROUNDS.KAEDIN.background,
		shortDescription: CAMPAIGN_02_BACKGROUNDS.KAEDIN.shortDescription,
	},
	{
		name: 'Soshi',
		race: 'Elf',
		class: 'Wizard',
		level: 6,
		icon: 'images/assets/character_thumbnails/campaign_002/soshi.jpeg',
		background: CAMPAIGN_02_BACKGROUNDS.SOSHI.background,
		shortDescription: CAMPAIGN_02_BACKGROUNDS.SOSHI.shortDescription,
	},
	{
		name: 'Norr',
		race: 'Human',
		class: 'Sorcerer',
		level: 6,
		icon: 'images/assets/character_thumbnails/campaign_002/norr.jpeg',
		background: CAMPAIGN_02_BACKGROUNDS.NORR.background,
		shortDescription: CAMPAIGN_02_BACKGROUNDS.NORR.shortDescription,
	},
	{
		name: 'Olek',
		race: 'Aasimar',
		class: 'Paladin',
		level: 6,
		icon: 'images/assets/character_thumbnails/campaign_002/olek.jpeg',
		background: CAMPAIGN_02_BACKGROUNDS.OLEK.background,
		shortDescription: CAMPAIGN_02_BACKGROUNDS.OLEK.shortDescription,
	},
];
