const CAMPAIGN_002_QUESTS = [
	{
		id: 1,
		title: "Investigate Wyrmlord Koth and 'Day of Ruin'",
		status: 'Active',
		priority: 'Critical',
		current_objective: 'Reach and destroy bridge to delay invasion army',
		sessions: [
			{
				session: 1,
				description: 'Quest initiated during hobgoblin ambush interrogation',
				details: [
					'Captured hobgoblin survivor after battle at abandoned farmhouse',
					'Olek cast Zone of Truth; hobgoblin agreed to answer in exchange for swift death',
					"Learned enemy leader: Wyrmlord Koth, gathering tribes for 'Day of Ruin'",
					'Details vague; exact location refused/unknown',
					'Hobgoblin released and killed per promise',
				],
			},
			{
				session: 2,
				description: 'Intelligence sharing with allies',
				details: [
					'Kaedin shared investigation details with Winter Rose mercenary June Takahashi',
					'Exchanged intel about raids and incursions in the region',
				],
			},
			{
				session: 4,
				description: 'Connected to larger conspiracy',
				details: [
					"Discovered monsters being collected for 'Festival of Life' with connection to Kilgor and Brotherhood",
					'No direct Wyrmlord Koth intelligence gained',
				],
			},
			{
				session: 6,
				description: 'Direct engagement with enemy forces',
				details: [
					'Attacked fortress in Witchwood',
					"Enemy shaman ordered retreat to 'alert the Wormlord' before escaping",
					'Confirmed Wyrmlord = Wormlord',
				],
			},
			{
				session: 7,
				description: 'Critical intelligence breakthrough',
				details: [
					'Discovered tactical maps in fortress showing massive invasion force',
					'Army estimated at 19× larger than previous engagements',
					"Approaching Drellin's Ferry with ETA of 4 days",
					'Red dragon confirmed involved (magical residue and claw marks found)',
					'Single bridge identified as strategic choke point',
					'Destroying bridge could delay invasion 2-3 days',
				],
			},
			{
				session: 8,
				description: 'Prophetic visions confirm scope',
				details: [
					"Visions revealed Wyrmlord Koth's forces part of massive alliance",
					'Blue Bear sigil identified as unifying command structure',
					'Alliance includes Red Hand, Black Orcs, Chromatic Dragons, and others',
					'Party prioritized bridge destruction to delay invasion',
					'Warning letter sent to Captain Soranna via Yoghurt',
				],
			},
		],
	},
	{
		id: 2,
		title: "Retrieve Dead Man's Boots from Nels Huto",
		status: 'Active',
		priority: 'Normal',
		current_objective: "Locate Nels Huto in Witchwood and retrieve Dead Man's Boots",
		sessions: [
			{
				session: 1,
				description: 'Quest initiated at Tollhouse',
				details: [
					'Bonnie delivered artifact from Rilon Paln to Sorana',
					"Sorana identified one item: Dead Man's Boots",
					'Last held by necromancer Nels Huto',
					'Target location: Witchwood',
					'Quest officially accepted',
				],
			},
			{
				session: '2-8',
				description: 'No progress recorded',
				details: [
					'Party focused on other urgent threats (hydra, temple, invasion)',
					'Witchwood explored but necromancer not encountered',
				],
			},
		],
	},
	{
		id: 3,
		title: 'Stop the Raiders',
		status: 'Active',
		priority: 'Critical',
		current_objective: 'Destroy bridge to delay invasion; raiders confirmed as part of massive coordinated assault',
		sessions: [
			{
				session: 1,
				description: 'Quest offered',
				details: [
					'Norro (elder at Tollhouse) offered reward for stopping raiders',
					'Raids ongoing; base likely deep in Witchwood',
					'Party accepted mission',
				],
			},
			{
				session: 2,
				description: 'First major engagement',
				details: [
					'Discovered rigged bridge with explosives',
					'Found massive mound of bodies in swamp beneath bridge',
					'Defeated hydra guarding area',
					'Bonnie disarmed all bridge traps and looted area',
					'Retreated to town after multiple warg rider ambushes',
				],
			},
			{
				session: 3,
				description: 'Reported findings',
				details: [
					'Briefed Captain Soranna at Tollhouse basement',
					'Recounted mauled corpses, green-cloaked figures, missing woodsman',
					'Soranna marked incidents on map with red-flagged pins',
					'Received 10 gold pieces reward',
					'Learned of secret cave system beneath city (potential invasion route)',
				],
			},
			{
				session: 4,
				description: 'Underground discovery',
				details: [
					'Explored cavern system',
					"Found evidence of Broken Shackle tribe answering 'call of the Red Hand' two weeks prior",
					'Learned of coordinated tribal movements',
				],
			},
			{
				session: 6,
				description: 'Major tactical success',
				details: [
					'Found burned caravan with 10 civilian casualties',
					'Tracked approximately 20 orcs on wargs northwest toward Witchwood',
					'Reached ruined fortress',
					'Launched surprise assault using Grease + Fireball combo',
					'Destroyed stable, killed multiple hobgoblins and wargs',
					'Defeated manticore, minotaur, mud elemental, and additional forces',
					'Enemy shaman and minotaur escaped through main gate',
					'Fortress left ablaze',
				],
			},
			{
				session: 7,
				description: 'Critical intelligence gathered',
				details: [
					'Discovered invasion force 19× previous size approaching in 4 days',
					'Bridge identified as key strategic target',
					"Party debated whether to warn or abandon Drellin's Ferry",
				],
			},
			{
				session: 8,
				description: 'Warning dispatched',
				details: [
					'Detailed warning letter written by Bonnie to Captain Soranna',
					'Letter included: approaching army details, ETA, visions, unified enemy forces, Arcane Brotherhood untrustworthiness',
					'Objective stated: immediate evacuation or reinforcement',
					'Yoghurt paid 3 gold to deliver to Soranna only (instructed not to show Cat)',
					'Primary focus shifted to destroying bridge to delay invasion',
				],
			},
		],
	},
	{
		id: 4,
		title: 'Investigate Witchwood and Wrath Keep',
		status: 'Active',
		priority: 'Normal',
		current_objective: 'Continue Witchwood exploration as secondary priority; main threats identified and engaged',
		sessions: [
			{
				session: 1,
				description: 'Quest information gathered',
				details: [
					'Avartel (druid) provided information at Shrine of Pelor',
					'Wrath Keep identified as cursed fortress with skeletons',
					'Witchwood confirmed as dangerous area with magical nexus',
					'Sertieren (wizard) confirmed magical nexus in Witchwood',
				],
			},
			{
				session: 2,
				description: 'Approach begun',
				details: ['Party moved off-road toward forest', 'Chose stealth approach to investigate area'],
			},
			{
				session: 6,
				description: 'Direct exploration',
				details: [
					'Traveled through Witchwood',
					'Forest appeared unnaturally lifeless',
					'Found ruined fortress with lingering abjuration and renewal magic',
					'Engaged enemy forces at fortress',
				],
			},
			{
				session: 7,
				description: 'Deeper infiltration',
				details: [
					'Explored fortress interior: throne room, lower tunnels, ritual chamber',
					'Found evidence of sealed vault and blood magic rituals',
					'Discovered Null Brand artifact in corrupted vault',
				],
			},
			{
				session: 8,
				description: 'Artifact destroyed',
				details: [
					'Null Brand shattered in explosion',
					'Corruption lifted from immediate area',
					'Fortress area partially cleared',
				],
			},
		],
	},
	{
		id: 5,
		title: 'Winter Rose Spider Bounty',
		status: 'Active',
		priority: 'Low',
		current_objective: 'Not actively pursued by party',
		sessions: [
			{
				session: 2,
				description: 'Quest learned',
				details: [
					'Winter Rose mercenaries (Vandal and Summoner) mentioned seeking large spider bounty',
					'Looking for target in eastern woods area',
					'No direct party involvement',
				],
			},
			{
				session: '3-8',
				description: 'Mentioned but not pursued',
				details: [
					'Vandal and Summoner encountered multiple times',
					'Party focused on other objectives',
					'Spider bounty remains unclaimed',
				],
			},
		],
	},
	{
		id: 6,
		title: 'Investigate Cave System',
		status: 'Completed',
		priority: 'Normal',
		current_objective: 'Quest completed',
		sessions: [
			{
				session: 3,
				description: 'Quest assigned and executed',
				details: [
					"Captain Soranna revealed vast cave system beneath Drellin's Ferry",
					'Potential secret invasion route identified',
					'Two agents (Kat and Yoghurt) assigned to guide party',
					'Magical barrier blocks city-affiliated people; only outsiders can pass',
					'Met with Kat (Tiefling with cats/tiger) and Yoghurt (half-ogre ninja)',
					'Entered partially submerged temple',
					'Party passed through magical barrier (thieves could not)',
					'Found stone ring with skeletal remains and weapons',
					"Two doors discovered: reptile carving (party's path) and storm cloud carving (mercenaries' path)",
					'Bypassed traps: poisonous gas, venomous snakes/spiders, flooded pond with giant leeches',
					'Used stealth, Pass Without Trace, Misty Step, Fly, and Echo teleportation',
					"Discovered laboratory with note detailing demon disciples' monster-breeding experiments",
					'Found treasure in water with piranhas, snakes, human-sized bats',
					'Defeated massive reptile (polymorphed into caterpillar by Soshi)',
					'Coordinated with mercenaries to press runes, collapsing arena skeletons',
					'Third passage opened; previous corridor sealed',
					'Successfully explored temple complex',
					"Mapped demon disciples' breeding facility",
					'Collapsed tunnels as instructed',
					'Received loot and leveled to 7',
				],
			},
			{
				session: 4,
				description: 'Escape',
				details: [
					'Continued through caverns',
					'Discovered pirate ship lodged in tunnel',
					'Vandal triggered explosion opening path',
					'Entire cave system collapsed behind them',
					'Emerged from mountain waterfall into sea',
				],
			},
		],
	},
	{
		id: 7,
		title: 'Rescue Anya',
		status: 'Completed',
		priority: 'Low',
		current_objective: 'Quest completed',
		sessions: [
			{
				session: 3,
				description: 'Quest initiated, investigated, and completed',
				details: [
					'Tharma (innkeeper) informed party that Anya (young assistant) had gone missing',
					"Party investigated Anya's home",
					'Found dried blood and love letter to Lem (town guard)',
					'Suspicious townsfolk observed from shadows',
					'Gossip revealed Anya romantically involved with multiple men until six months prior',
					'Visited Lem at barracks',
					'Lem: young, pudgy human guard (~1.5m tall)',
					'Confessed to casual relationship with Anya',
					'Unaware of her pregnancy',
					'Revealed meeting spot near forest pond',
					'Described recent worg rider attack (minor injuries)',
					'Located Anya at forest pond',
					'Found her weak, bleeding, delirious, attempting suicide',
					'Kaedin rendered her unconscious for safe transport',
					'Bonnie comforted her during extraction',
					"Transported to Avarthel's grove",
					'Loïc (phoenix) shed healing tears to stabilize Anya',
					'Avarthel agreed to escort Anya deeper into forest for long-term recovery',
					"Anya's safety secured",
				],
			},
		],
	},
	{
		id: 8,
		title: 'Hydra Egg Safekeeping',
		status: 'Completed',
		priority: 'Normal',
		current_objective: 'Quest completed',
		sessions: [
			{
				session: 2,
				description: 'Problem discovered',
				details: [
					'Soshi discovered two hydra eggs in her pack after battle',
					'Warmth and humidity putting eggs at risk of hatching',
					'Party concerned about dangerous hatchlings',
				],
			},
			{
				session: 3,
				description: 'Solution sought and resolved',
				details: [
					'Visited Avarthel (druid) at his grove',
					'Avarthel refused to hatch eggs, citing ecological danger',
					'Agreed to store eggs securely',
					'Revealed only druids in Ramashen could safely return eggs to Feywild',
					"Eggs transferred to Avarthel's secure storage",
					'Long-term care plan established',
					'Party relieved of dangerous cargo',
				],
			},
		],
	},
	{
		id: 9,
		title: 'Retrieve Locket of Hair from Sandro',
		status: 'Active',
		priority: 'Low',
		current_objective: 'Locate Sandro using carved whistle and retrieve hair locket in exchange for magical compass',
		sessions: [
			{
				session: 5,
				description: 'Quest offered',
				details: [
					"Aboard The Leviathan's Hall, Turiados's magical compass pointed at Soshi",
					"Compass reveals 'direction of one's greatest desire'",
					'Turiados offered to trade compass if party brings locket of hair from necromancer Sandro',
					'Carved whistle provided as guide to target',
					"Background: Sandro murdered Bianca's father and usurped Pelagos throne",
				],
			},
			{
				session: '6-8',
				description: 'Not pursued',
				details: [
					'Party focused on immediate threats (invasion, fortress assault)',
					'Quest remains available but not prioritized',
				],
			},
		],
	},
	{
		id: 10,
		title: "Investigate 'The Brotherhood' Activities",
		status: 'Active',
		priority: 'High',
		current_objective:
			'Brotherhood confirmed as major antagonist faction in coming apocalypse; party members are defectors/enemies',
		sessions: [
			{
				session: 1,
				description: 'Initial connection',
				details: [
					'Soshi and Norr revealed as former Arcane Brotherhood trainees',
					'Escaped with Norr; fled with treasure map',
					'Brotherhood noted as recently uncooperative',
				],
			},
			{
				session: 4,
				description: 'Major discovery',
				details: [
					"Found Calistra's camp in caverns",
					'Half-burned ledger recovered with Brotherhood references',
					"Ledger revealed: Calistra collecting arena creatures for Kilgor, Brotherhood failed to send reinforcements, Three harpy spies sent by Kilgor suspected, Plans to deliver creatures for 'Festival of Life', Travel to Luskan via pirates, Treasure at 'old fort north of the woods', Signed by 'Calistra of the Brotherhood'",
					'Norr recognized Calistra as former teacher (alteration specialist)',
					'Calistra left Brotherhood 10 years prior',
					'Illusion script ward prevented full ledger reading',
				],
			},
			{
				session: 5,
				description: 'Identity compromised',
				details: [
					'Bianca identified Soshi as Brotherhood member',
					"Probed Soshi's motives; Soshi deflected",
					'Revealed Bianca and Turiados stole relics from Brotherhood',
					"Sertieren confirmed he was Calistra's former companion",
					'Calistra joined Brotherhood before their relationship ended',
					'Sertieren warned of portentous events',
				],
			},
			{
				session: 7,
				description: 'Ritual chamber discovery',
				details: [
					"Found Thieves' Cant markings linking both Arcane Seekers and Brotherhood",
					"Both factions involved in sealed vault's history",
					'Blood-binding ritual connected to Brotherhood operations',
				],
			},
			{
				session: 8,
				description: 'Catastrophic revelation',
				details: [
					'Prophetic visions revealed Brotherhood allied with invasion forces',
					"Soshi's vision: Arcane Brotherhood mages commanding siege of Neverwinter",
					'Brotherhood working alongside Red Wizards of Thay, Blue Bear forces, chromatic dragons',
					'Warning letter to Soranna specifically noted Brotherhood untrustworthiness',
				],
			},
		],
	},
	{
		id: 11,
		title: "Locate Kilgor's Festival",
		status: 'Active',
		priority: 'High',
		current_objective: "Locate festival site and determine Kilgor's true nature and goals",
		sessions: [
			{
				session: 4,
				description: 'Quest information discovered',
				details: [
					"Calistra's ledger mentioned 'Festival of Life'",
					'All collected arena creatures destined for Kilgor',
					'Festival purpose: unknown',
					"Treasure cache mentioned at 'old fort north of the woods'",
				],
			},
			{
				session: 8,
				description: 'Additional context',
				details: [
					"Bonnie's vision revealed Kilgor as warrior who defeated Fey Queens",
					'Kilgor seized crowns of Titania and Queen of Air and Darkness',
					'Led army that withered the Feywild',
					'Associated with Red Hand, Black Orcs, Blue Bear forces',
				],
			},
		],
	},
	{
		id: 12,
		title: 'Care for Thylacoleo Cubs',
		status: 'Active',
		priority: 'Normal',
		current_objective: 'Seven cubs secured and traveling with party; magical properties lost after artifact explosion',
		sessions: [
			{
				session: 5,
				description: 'Cubs acquired and initial care',
				details: [
					'After defeating three adult Thylacoleos in oak forest ambush',
					'Discovered seven cubs in tree hollow',
					'Party decided to care for them rather than abandon',
					"Avarthel's grove empty (snake guardian said he'd be gone for months)",
					'Brother Danny at shrine unhelpful',
					'Goat-herd provided milk in exchange for gold',
					'Visited Sertieren the Wise for solution',
					'Sertieren offered containment spheres (1 gold each)',
					'Required magical naming attunement',
					'Bonnie took magical debt brand on wrist as collateral',
					'Cubs named and stored: Bonnie (Tom and Garfield), Soshi (Milly and Yoli), Kaedin (Avatar and Bella), One unnamed',
				],
			},
			{
				session: 6,
				description: 'Feline chaos and travel',
				details: [
					'Party released cubs at inn for 48-hour maturation period',
					"Kaedin's cats escaped through wall, hunted numerous animals (mice, pigeons, dogs, cats, seagull)",
					'Massive hole created in inn wall leading to street',
					"Norr's cat climbed walls and ceilings",
					"Olek's cat (Palo) raided kitchen (stew, milk, honey)",
					"Bonnie's and Soshi's cats well-behaved",
					'Town covered with missing pet posters',
					'Innkeeper demanded 5 silver per night for repairs',
					'All cats returned to spheres for safety',
					'Cubs released during travel to fortress',
					'Cats traveling alongside party',
				],
			},
			{
				session: 8,
				description: 'Survived explosion',
				details: [
					'Feline companions survived Null Brand explosion',
					'Now mundane cats (no longer magical)',
					'Still with party',
				],
			},
		],
	},
	{
		id: 13,
		title: 'Investigate Missing Barbarian Riders',
		status: 'Active',
		priority: 'Normal',
		current_objective: 'Locate four missing barbarian riders in Witchwood when time permits',
		sessions: [
			{
				session: 6,
				description: 'Quest assigned',
				details: [
					'Captain Sorana assigned investigation during barracks visit',
					'Four barbarian riders missing',
					'Last seen in Witchwood, northwest of town',
					'Quest accepted but not immediately pursued',
				],
			},
			{
				session: '7-8',
				description: 'No progress',
				details: [
					'Party entered Witchwood area and engaged fortress',
					'No riders encountered or evidence found',
					'Focus shifted to invasion threat',
				],
			},
		],
	},
	{
		id: 14,
		title: 'Prevent Prophesied Future',
		status: 'Active',
		priority: 'Critical',
		current_objective:
			"Prevent apocalyptic future by disrupting enemy alliance's coordinated plans; starting with delaying Drellin's Ferry invasion",
		sessions: [
			{
				session: 8,
				description: 'Quest initiated through visions and pattern analysis',
				details: [
					'Null Brand explosion threw each party member into prophetic visions',
					'Each vision showed different aspect of apocalyptic future',
				],
				visions: [
					{
						characters: ['Olek', 'Norr'],
						vision:
							"Corrupted Paladin fortress overrun by crystalline blight. Lamashtu cults infiltrated Paladin order after Battle for Bremen. Fortress fell to Angevin fleet landing with resurrected god Kresimir. Norr's future self missing right arm.",
					},
					{
						characters: ['Kaedin'],
						vision:
							'Neighboring village burned by Blue Bear slavers and cultists. Children spoke of ritual sacrifices. His home village targeted next.',
					},
					{
						characters: ['Bonnie'],
						vision:
							"Catastrophic Feywild war. Titania and Queen of Air and Darkness fighting together against Kilgor. Spring and Autumn Courts annihilated. Chromatic dragons decimated Feywild defenses. Nine Paladins of Neverwinter as last defenders. Kilgor seized both queens' crowns, withering the Feywild. Enemy banners: Red Hand, Black Orcs, Blue Bear.",
					},
					{
						characters: ['Soshi'],
						vision:
							'Chained among hundreds at siege of Neverwinter. Red Wizards of Thay leading assault. Arcane Brotherhood mages commanding forces. Blue Bear banners present. Chromatic dragons overhead. Mass prisoner sacrifice ritual to destroy city walls.',
					},
				],
				recurring_elements: {
					unifying_banner: 'Blue Bear sigil',
					alliance: [
						'Red Hand',
						'Black Orcs',
						'Chromatic Dragons',
						'Lamashtu Cults',
						'Arcane Brotherhood',
						'Red Wizards of Thay',
					],
					pivotal_event: 'Battle for Bremen',
					strategy: 'Coordinated multi-front assault on major powers',
				},
				first_countermeasure: [
					'Immediate action: delay invasion to disrupt timeline',
					"Warning sent to Drellin's Ferry",
					'Primary objective: destroy bridge',
				],
			},
		],
	},
	{
		id: 15,
		title: 'Destroy the Bridge',
		status: 'Active',
		priority: 'Critical',
		current_objective: 'Reach bridge before invasion army and destroy it to delay advance by 2-3 days',
		sessions: [
			{
				session: 7,
				description: 'Strategic target identified',
				details: [
					'Tactical maps in fortress revealed invasion route',
					"Single bridge identified as choke point en route to Drellin's Ferry",
					'Destroying bridge could delay army 2-3 days',
					'Party debated prioritization',
				],
			},
			{
				session: 8,
				description: 'Mission committed',
				details: [
					'After visions confirmed stakes of failure',
					'Party unanimously resolved to destroy bridge',
					"Objective: buy time for Drellin's Ferry and disrupt invasion timeline",
					'Warning letter sent ahead via Yoghurt',
					'Party departed fortress heading toward bridge',
				],
			},
		],
	},
	{
		id: 16,
		title: "Warn Drellin's Ferry",
		status: 'Active',
		priority: 'High',
		current_objective: 'Warning en route; outcome unknown; party proceeding to bridge destruction',
		sessions: [
			{
				session: 7,
				description: 'Debate initiated',
				details: [
					'After discovering invasion force intelligence',
					'Party split on whether to warn or abandon town',
					'Some argued townsfolk ignored prior warnings',
					'Others felt obligation to provide warning',
					'Messaging via familiars dismissed due to range limits',
				],
			},
			{
				session: 8,
				description: 'Warning composed and sent',
				details: [
					'Bonnie wrote detailed letter to Captain Soranna',
					'Contents included: Approaching army details and size, ETA: 4 days, Prophetic visions of future, Unified enemy force composition, Warning about Arcane Brotherhood untrustworthiness, Recommendation: immediate evacuation or reinforcement',
					'Yoghurt hired for 3 gold pieces as courier',
					'Strict instructions: deliver to Soranna only, do not show Cat',
					'Yoghurt repeated instructions and departed into woods',
				],
			},
		],
	},
	{
		id: 17,
		title: 'Investigate Blue Bear Sigil',
		status: 'Active',
		priority: 'Critical',
		current_objective:
			'Identify Blue Bear leadership, organization, and strategic goals while disrupting their invasion plans',
		sessions: [
			{
				session: 8,
				description: 'Threat identified and alliance structure recognized',
				details: [
					"Blue Bear sigil appeared in all party members' prophetic visions",
					"Kaedin's vision: Blue Bear forces leading village attack and slave-taking",
					"Bonnie's vision: Blue Bear banners among Feywild invasion force",
					"Soshi's vision: Blue Bear banners at Neverwinter siege",
					'Identified as unifying command structure across all enemy forces',
					'Blue Bear confirmed as primary coordinating faction',
				],
				allied_forces: [
					'Red Hand',
					'Black Orcs',
					'Chromatic Dragons',
					'Lamashtu Cults',
					'Arcane Brotherhood',
					'Red Wizards of Thay',
				],
				threat_assessment: 'Multi-front coordinated assault planned',
			},
		],
	},
	{
		id: 18,
		title: 'Investigate the Null Brand',
		status: 'Completed',
		priority: 'Critical',
		current_objective: 'Quest completed',
		sessions: [
			{
				session: 7,
				description: 'Artifact discovered and tense negotiation',
				details: [
					'Found in final vault of corrupted temple',
					'Black iron brand shaped like broken star',
					'Glowing with red runes',
					'Radiating corruption throughout blackstone chamber',
					'Kalistra bound to it by arcane chains',
					"Using her life force to contain artifact's energy",
					'Kalistra requested aid to stabilize the Brand',
					'Hinted at plans to later claim it for Brotherhood',
					'Party planned contingencies (Hold Person, Counterspell, Grapple)',
					'Before action: red dragonkin and 20 orcs arrived',
					'Dragon commanded forces to breach and take artifact',
				],
			},
			{
				session: 8,
				description: 'Final battle and destruction',
				details: [
					'Red-armored army breached ritual chamber wall',
					'Massive battle erupted (hobgoblins, orcs, dragonkin, archers)',
					'Bonnie assassinated one dragonkin shaman',
					'Ritualist (Kalistra?) killed during combat',
					"Artifact destabilized without ritualist's control",
					'Null Brand emitted wave of necrotic energy',
					'Began spinning violently, glowing brighter',
					'Explosion imminent; party took cover',
					'Artifact detonated, obliterating chamber',
					'Each party member thrown into individual prophetic visions',
					'Explosion subsided leaving chamber in ruins',
					'Artifact shattered; corruption lifted',
					'Air clean but heavy with aftermath',
				],
			},
		],
	},
];
