const CAMPAIGN_001_CHARACTERS = [
	{
		name: 'Aenwyn',
		class: 'Sorcerer',
		race: 'Elf',
		level: 8,
		icon: 'images/assets/character_thumbnails/campaign_001/aenwyn.jpeg',
		background: null,
		shortDescription: null,
		stats: {
			abilityScores: null,
			metadata: CAMPAIGN_001_METADATA.AENWYN,
		},
		is_included: true,
	},
	{
		name: 'Aethere',
		class: 'Bard',
		race: 'Half-Elf',
		level: 8,
		icon: 'images/assets/character_thumbnails/campaign_001/aethere.jpeg',
		background: null,
		shortDescription: null,
		stats: {
			abilityScores: null,
			metadata: CAMPAIGN_001_METADATA.AETHERE,
		},
		is_included: true,
	},
	{
		name: 'Alezander',
		class: 'Barbarian',
		race: 'Half-Orc',
		level: 8,
		icon: 'images/assets/character_thumbnails/campaign_001/alezander.jpeg',
		background: null,
		shortDescription: null,
		stats: {
			abilityScores: null,
			metadata: CAMPAIGN_001_METADATA.ALEZANDER,
		},
		is_included: true,
	},
	{
		name: 'Nora',
		class: 'Ranger',
		race: 'Half-Elf',
		level: 8,
		icon: 'images/assets/character_thumbnails/campaign_001/nora.png',
		background: null,
		shortDescription: null,
		stats: {
			abilityScores: null,
			metadata: CAMPAIGN_001_METADATA.NORA,
		},
		is_included: true,
	},
	{
		name: 'Samantha',
		class: 'Cleric',
		race: 'Halfling',
		level: 8,
		icon: 'images/assets/character_thumbnails/campaign_001/samantha.jpeg',
		background: null,
		shortDescription: null,
		stats: {
			abilityScores: null,
			metadata: CAMPAIGN_001_METADATA.SAMANTHA,
		},
		is_included: true,
	},
	{
		name: 'Smasherina',
		class: 'Barbarian',
		race: 'Halfling',
		level: 8,
		icon: 'images/assets/character_thumbnails/campaign_001/smasherina.jpg',
		background: null,
		shortDescription: null,
		stats: {
			abilityScores: null,
			metadata: CAMPAIGN_001_METADATA.SMASHERINA,
		},
		is_included: true,
	},
];
