const CAMPAIGN_01_RECAPS = [
	{
		id: 'session-001',
		title: 'Introduction',
		date: 'N/A',
		content: 'session_data/session_001/session_001_content.md',
		recap: 'session_data/session_001/session_001_recap.md',
	},
	{
		id: 'session-002',
		title: '002 - Race Against Time',
		date: 'N/A',
		content: 'session_data/session_002/session_002_content.md',
		recap: 'session_data/session_002/session_002_recap.md',
	},
	{
		id: 'session-004',
		title: '004 - Journey to Korinis',
		date: 'N/A',
		content: 'session_data/session_004/session_004_content.md',
		recap: 'session_data/session_004/session_004_recap.md',
	},
	{
		id: 'session-006',
		title: '006 - Trials in the Wilds',
		date: 'N/A',
		content: 'session_data/session_006/session_006_content.md',
		recap: 'session_data/session_006/session_006_recap.md',
	},
	{
		id: 'session-007',
		title: '007 - Shadows in the Forest',
		date: 'N/A',
		content: 'session_data/session_007/session_007_content.md',
		recap: 'session_data/session_007/session_007_recap.md',
	},
	{
		id: 'session-010',
		title: '010 - Secrets Beneath the Sand',
		date: 'N/A',
		content: 'session_data/session_010/session_010_content.md',
		recap: 'session_data/session_010/session_010_recap.md',
	},
	{
		id: 'session-011',
		title: '011 - Chaos and Chocolate',
		date: 'N/A',
		content: 'session_data/session_011/session_011_content.md',
		recap: 'session_data/session_011/session_011_recap.md',
	},
	{
		id: 'session-012',
		title: '012 - Secrets in the Penal Colony',
		date: 'N/A',
		content: 'session_data/session_012/session_012_content.md',
		recap: 'session_data/session_012/session_012_recap.md',
	},
	{
		id: 'session-013',
		title: '013 - Battles & Bargains',
		date: 'N/A',
		content: 'session_data/session_013/session_013_content.md',
		recap: 'session_data/session_013/session_013_recap.md',
	},
	{
		id: 'session-014',
		title: '014 - Arcane Paths',
		date: 'N/A',
		content: 'session_data/session_014/session_014_content.md',
		recap: 'session_data/session_014/session_014_recap.md',
	},
	{
		id: 'session-015',
		title: '015 - The Blood Ritual',
		date: 'N/A',
		content: 'session_data/session_015/session_015_content.md',
		recap: 'session_data/session_015/session_015_recap.md',
	},
];
