const CAMPAIGN_002_LOCATIONS = [
	{
		id: 'drellins-ferry',
		name: "Drellin's Ferry",
		type: 'town',
		region: 'Elsir Vale',
		description:
			'A town spread along a river where rope ferries operate where a bridge once stood. Watchtowers loom above orchards and fields. The town is aware of nearby dangers and faces coordinated raider attacks.',
		features: [
			'Rope ferries across river',
			'Watchtowers',
			'Orchards and fields',
			'Tollhouse',
			'Barracks',
			'Shrine of Pelor',
			"Sertieren's Mansion",
			'Old Bridge Inn / Green Apple Inn',
			'General Store',
			"Armorer's Forge",
			'Shopping District',
			'Underground cave system (sealed by light barrier)',
		],
		npcs: [
			'Captain Soranna',
			'Councilman Norro',
			'Sergeant Hersk',
			'Brother Denny',
			'Avartel (left for mountains)',
			'Sertieren (planning to leave)',
			'Tarma',
			'Kat',
			'Yoghurt',
			'Anya (left with Avarthel)',
			'Lem',
			'Jareth',
			'Jaret',
			'Dwarf Armorer',
		],
		connections: [
			'Witchwood (northwest, several hours travel)',
			'Brindol (accessible via trade routes)',
			'Bridge (one day northeast - strategic target)',
			'Ruined Fortress (in Witchwood)',
		],
		threats: [
			'Coordinated raider attacks',
			'Army approaching in 4 days (as of Session 8)',
			'Underground cave infiltration route',
			'Approaching horde of 30+ units',
		],
	},
	{
		id: 'witchwood',
		name: 'The Witchwood',
		type: 'region',
		region: 'Elsir Vale',
		description:
			"A dense, dangerous forest to the northwest of Drellin's Ferry. Parts of it are corrupted by blighted magic that creates illusions and distorts perception. Undead are rumored to wander its borders.",
		features: [
			'Dense oak forest',
			'Blighted areas with illusion magic',
			'Twisted, dead trees',
			'Brooks and clearings',
			'Ancient ruins',
			'Swamplands',
		],
		connections: [
			"Drellin's Ferry (several hours southeast)",
			'Wrath Keep (deep within)',
			'Ruined Fortress (within forest)',
			'Secret meeting pond (4 hours walk from town)',
		],
		threats: [
			'Hobgoblin raiders',
			'Worgs and worg riders',
			'Undead',
			'Thylacoleos',
			'Raptors',
			'Hydras',
			'Blighted magic corruption',
		],
	},
	{
		id: 'wrath-keep',
		name: 'Wrath Keep',
		type: 'fortress',
		region: 'The Witchwood',
		description:
			'A cursed fortress deep in the Witchwood, guarded by undead. The area is dangerous and avoided by locals.',
		history: 'An ancient fortress that fell to a curse. Now inhabited by undead guardians.',
		features: ['Cursed grounds', 'Undead guardians'],
	},
	{
		id: 'old-bridge-inn',
		name: 'Old Bridge Inn / Green Apple Inn',
		type: 'other_structure',
		region: "Drellin's Ferry",
		description:
			'A welcoming inn run by the dwarf Tarma. Serves as the primary lodging for adventurers and travelers. Known for hearty breakfasts and experimental cuisine.',
		features: ['Common room', 'Multiple guest rooms', 'Kitchen', 'Bar area'],
		npcs: ['Tarma (proprietress)', 'Various barmaid staff', 'Anya (former assistant - missing)'],
	},
	{
		id: 'sertierten-mansion',
		name: "Sertieren's Mansion",
		type: 'other_structure',
		region: "Drellin's Ferry",
		description:
			"A wizard's mansion featuring a magical fountain and animated armor guards. Home to the eccentric wizard Sertieren.",
		features: ['Magical fountain entrance', 'Animated armor guardians', 'Laboratory', 'Extensive library'],
		npcs: ['Sertieren', 'Halfling servant'],
	},
	{
		id: 'shrine-of-pelor',
		name: 'Shrine of Pelor',
		type: 'other_structure',
		region: "Drellin's Ferry",
		description: 'A religious shrine dedicated to Pelor, maintained by Brother Denny and other clerics.',
		npcs: ['Brother Denny', 'Avartel (formerly)'],
	},
	{
		id: 'avarthel-grove',
		name: "Avarthel's Grove",
		type: 'other_structure',
		region: "Near Drellin's Ferry",
		description:
			"A beautiful magical grove at the forest's edge with proximity to the Feywild. The grove has positive effects on visitors, particularly those with Fey heritage.",
		features: [
			'Feywild connection',
			'Healing properties',
			'Giant snake guardian',
			'Size-enhancing effects on Fey creatures',
		],
		npcs: ['Avarthel (left for mountains)', 'Loic (Phoenix)', 'Giant snake guardian'],
		history: 'Created by Avarthel. Left abandoned when he departed for the mountains.',
	},
	{
		id: 'dusk-way',
		name: 'The Dusk Way',
		type: 'region',
		region: "Between Drellin's Ferry and Witchwood",
		description:
			'A treacherous path through swampland leading into the Witchwood. Critical trade route that raiders are attempting to close off.',
		features: ['Swamplands', 'Wooden bridge (trapped)', 'Dense forest', 'Tall grass and broken fences'],
		threats: ['Hobgoblin ambushes', 'Hydra', 'Bear traps', 'Worg riders'],
	},
	{
		id: 'bridge-ambush',
		name: 'Bridge Ambush Site',
		type: 'other_structure',
		region: 'The Dusk Way',
		description:
			'A wooden bridge over murky swamp water where hobgoblins set up an elaborate ambush with a five-headed hydra.',
		history:
			'Site of major battle where party defeated hydra and raiders. At least 10 travelers were killed and partially eaten here.',
		features: ['Wooden bridge with trap mechanisms', 'Swamp beneath', 'Concealed bear traps (30+ dismantled by party)'],
	},
	{
		id: 'underground-temple',
		name: 'Underground Temple Complex',
		type: 'dungeon',
		region: "Beneath Drellin's Ferry",
		description:
			'A vast underground complex with flooded caves, an arena, and laboratory chambers. Protected by a barrier of light that prevents city-affiliated people from passing.',
		history:
			"Ancient temple used for gladiatorial games and creature breeding experiments by Kalistra and disciples. They opened gates to Demon Lords' domains to capture creatures.",
		features: [
			'Arena with skeletal remains',
			'Laboratory with experiment tables',
			'Flooded chambers with piranhas and snakes',
			'Pit with giant leeches',
			'Cave system with giant bats',
			'Rune-activated mechanisms',
			'Light barrier entrance',
			'Stone entryway with indecipherable runes',
			'Superior ring (6 meters wide) overlooking arena',
			'Two entrance tunnels (reptile and lightning-marked)',
		],
		npcs: ['Kalistra (deceased - found here)', 'Various deceased disciples'],
		items: [
			'Laboratory notes about breeding program',
			'Experiment logs',
			'Red glowing chest underwater',
			'Various creature remains',
		],
		threats: [
			'Giant reptile creature',
			'Spiders',
			'Giant snakes',
			'Giant leeches',
			'Piranhas',
			'Giant bats',
			'Traps (fire and poison)',
		],
	},
	{
		id: 'ruined-fortress',
		name: 'Ruined Fortress',
		type: 'fortress',
		region: 'The Witchwood',
		description:
			'An ancient fortress with a strange cleansed feeling despite being occupied by raiders. Features crumbling walls, a central keep, and various outbuildings.',
		history:
			'Recently occupied by Red Hand forces as a staging ground. Site of major battle where party fought hobgoblins, worg riders, manticore, minotaur, and mud elemental.',
		features: [
			'Main courtyard with boulders',
			'Stables (burned during battle)',
			'Ruined tower with caved-in roof',
			'Main keep with single battlement',
			'Barracks',
			'Underground tunnels',
			'Throne room',
			'Torture chamber',
			'Map room with tactical intelligence',
		],
		npcs: ['Skeleton patrol (defeated)', 'Hobgoblin forces (defeated)', 'Orc shaman (fled)', 'Minotaur (fled)'],
		items: ['Map showing troop movements', 'Intelligence about 30-unit army', 'Bridge location marked'],
		connections: ['Underground passages', 'Vault chamber (below)', 'Strategic bridge (one day northeast)'],
	},
	{
		id: 'vault-chamber',
		name: 'The Vault / Null Brand Chamber',
		type: 'dungeon',
		region: 'Beneath Ruined Fortress',
		description:
			'A vast blackstone chamber housing the Null Brand artifact. The ground is barren dirt, all vegetation reduced to ash. Heavy, oppressive atmosphere with metallic tang.',
		history:
			"Ancient vault designed to contain the Null Brand. Kalistra sacrificed herself here to contain the artifact's corruption. Site of major battle with Red Hand forces and dragon.",
		features: [
			'Blackstone walls (cracked and scorched)',
			'Central pedestal',
			'Arcane chain bindings',
			'Ritual circle (blood magic)',
			'Multiple corpses of previous ritualists',
			'Skeletal remains with magical boots',
		],
		npcs: ['Kalistra (deceased, fused to artifact)', 'Red dragon (retreated)', '20 armored orcs (battle)'],
		items: [
			'Null Brand artifact (shattered)',
			'Belt of Strength 18',
			'Amulet of magical absorption',
			'The Deama Sutrel book',
			'Bone flute',
			'Peculiar mushrooms',
			'Magical boots',
		],
		threats: ['Corrupt magic fluctuations', 'Wild magic effects', 'Necrotic energy waves', 'Red Hand forces'],
	},
	{
		id: 'ritual-chamber',
		name: 'Blood Ritual Chamber',
		type: 'dungeon',
		region: 'Underground Complex',
		description:
			'A circular stone chamber with painted runes and a large ritual circle stained with dried blood. The air occasionally shimmers with whispers.',
		history:
			'Site where multiple people including Kalistra and her followers sacrificed themselves to open a sealed door using blood magic.',
		features: [
			'Ritual circle with blood channels',
			'Crumbled rune paintings',
			'Multiple corpses frozen in death poses',
			'Sealed stone door',
			'Torture equipment',
			'Merchant corpses',
			"Thieves' Cant markings",
		],
		npcs: ['Spectral guardians (defeated)', 'Kalistra (deceased)', 'Multiple deceased ritualists'],
		threats: [
			'Blood magic ritual requirements',
			'Spectral attackers',
			'Memory-stealing attacks',
			'Soul-binding effects',
		],
	},
	{
		id: 'megatherium-chamber',
		name: 'Megatherium Chamber',
		type: 'dungeon',
		region: 'Underground Cave System',
		description:
			'A large cavern housing two Megatherium (giant prehistoric sloth-bear-elephants). The creatures generate amber light from their bodies.',
		features: [
			'Glowing crystals',
			'Giant mosquito creatures',
			'Ramshackle saddle',
			'Underground lake',
			'Tunnel to shipwreck (90 feet underwater)',
		],
		npcs: ['Gică (Megatherium - befriended)', 'Mișu (Megatherium - befriended)'],
		history: 'Abandoned by Broken Shackle tribe members who answered "red hand" call two weeks prior.',
	},
	{
		id: 'leviathan-hall',
		name: "The Leviathan's Hall",
		type: 'other_structure',
		region: 'Coastal Waters',
		description:
			'A massive warship with black wood and green-tinged sails. Serves as mobile base for a pirate-paladin alliance.',
		features: [
			'Rows of cannons',
			'Forge operated by Efreeti and dwarf',
			'Bridge with commanders',
			'Crew quarters',
			'Storage for plundered goods',
		],
		npcs: [
			'Commander Turiados',
			'Commander/Queen Bianca',
			'Glass (Quartermaster)',
			'Marise Curs',
			'Bardin Cratcho',
			'Efreeti forge master',
			'Mixed crew of pirates and paladins',
			'Minotaurs',
			'Troglodytes',
		],
		history:
			'Stolen by Bianca with help from General Ilie. Crewed by freed penal colony prisoners bound by blood loyalty to House Corina.',
		connections: ['Lost at sea (searching for Pelagos)', 'Raided three ships from Brindol'],
	},
	{
		id: 'brindol',
		name: 'Brindol',
		type: 'city',
		region: 'Unknown',
		description: "A city with a dry dock and home to the Lion's Guard. Trade hub that has been raided by pirates.",
		npcs: ['Captain Hans Mariner'],
		connections: ["Drellin's Ferry (via trade routes)", "Coast (raided by Leviathan's Hall)"],
	},
	{
		id: 'pelagos',
		name: 'Pelagos',
		type: 'city',
		region: 'Lustria Continent',
		description:
			'A kingdom on the Lustria continent, now ruled by the necromancer Sandro. Formerly ruled by House Corina.',
		history:
			'Fell into civil war after lizardfolk mysteriously retreated. Sandro emerged, killed the king, and seized the throne.',
		npcs: ['Sandro (current tyrant)', 'House Corina (exiled)'],
	},
	{
		id: 'nautica',
		name: 'Nautica',
		type: 'region',
		region: 'Southern Seas',
		description: 'A pirate archipelago far to the south across the Shining Sea.',
		connections: ['Far south of current campaign area'],
	},
	{
		id: 'strategic-bridge',
		name: 'Strategic Bridge',
		type: 'other_structure',
		region: 'One day northeast of Ruined Fortress',
		description:
			"A critical bridge that the approaching Red Hand army must cross to reach Drellin's Ferry. Destroying it would delay the army by 2-3 days.",
		history: 'Identified from captured tactical maps as key chokepoint in enemy advance.',
		threats: ['Likely guarded by enemy forces', '30-unit army approaching'],
	},
	{
		id: 'lustria',
		name: 'Lustria',
		type: 'region',
		region: 'Another Continent',
		description: 'A distant continent with deep jungles and lizardfolk. Home to Pelagos and site of recent conflicts.',
		history:
			'Experienced mysterious regrowth of deep jungles causing lizardfolk to retreat, followed by civil wars among human kingdoms.',
		connections: ['Pelagos (kingdom)', 'Separated from current continent by ocean'],
	},
	{
		id: 'feywild',
		name: 'The Feywild',
		type: 'region',
		region: 'Parallel Plane',
		description:
			"The plane of the Fey, ruled by seasonal courts. Connected to the material plane in places like Avarthel's grove.",
		history:
			'In a possible future, witnessed under siege by chromatic dragons and Red Hand forces. Both Summer and Winter Queens fell.',
		features: [
			'Summer Court (Titania)',
			'Winter Court (Queen of Air and Darkness)',
			'Spring Court (annihilated in vision)',
			'Autumn Court (annihilated in vision)',
			'Pegasus knights',
			'Hippogriff riders',
		],
		threats: [
			'Chromatic dragons (in vision)',
			'Red Hand forces (in vision)',
			'Blue Bear faction (in vision)',
			'Energy-spear warrior (in vision)',
		],
	},
	{
		id: 'neverwinter',
		name: 'Neverwinter',
		type: 'city',
		region: 'The North',
		description: 'One of the greatest cities in the North. High walls, well-defended.',
		history: "In Soshi's vision, under siege by combined forces using prisoners as ritual fuel to bring down walls.",
		threats: [
			'Red Wizards of Thay (in vision)',
			'Arcane Brotherhood (in vision)',
			'Blue Bear faction (in vision)',
			'Chromatic dragons (in vision)',
		],
	},
	{
		id: 'bremen',
		name: 'Bremen',
		type: 'city',
		region: "Near Olek's Home",
		description: 'A strategic location that will be the site of a major battle that depletes paladin forces.',
		history:
			'In vision, "Battle for Bremen" results in massive casualties for paladin orders, forcing them to take unvetted recruits who turn out to be Lamashtu cultists.',
		threats: ['Angevin fleet (in vision)', 'Resurrected god Kresimir (in vision)', 'Red Hand forces (in vision)'],
	},
	{
		id: 'paladin-fortress',
		name: 'Blighted Paladin Fortress',
		type: 'fortress',
		region: 'Unknown',
		description: "A fortress of a paladin order close to Olek's own, seen in vision corrupted by crystalline growths.",
		history:
			'In vision, infiltrated by Lamashtu cultists after Battle for Bremen. Commander impaled and transformed by blight.',
		features: ['Stone walls with crystalline corruption', 'Watchtower', 'Courtyard'],
		threats: ["Lamashtu's cults (in vision)", 'Blighted corruption'],
	},
	{
		id: 'kaedins-village',
		name: "Kaedin's Village",
		type: 'village',
		region: 'Unknown',
		description: "Kaedin's home village, next to another village that was destroyed in his vision.",
		threats: ['Blue Bear clan (in vision)', 'Red Hand (in vision)', 'Slaver raids (in vision)'],
	},
];
