const CAMPAIGN_002_NPCS = [
	{
		id: 'soranna',
		name: 'Captain Soranna',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Unknown',
		class: 'Unknown',
		role: 'Town Guard Captain / Intelligence Operative',
		description:
			"The captain of Drellin's Ferry's guard and a skilled intelligence operative who coordinates investigations into the raider threats.",
		personality: 'Professional, strategic, and pragmatic. Takes security threats seriously.',
		location: "Drellin's Ferry - Tollhouse/Barracks",
		goals: [
			"Protect Drellin's Ferry from raiders",
			'Gather intelligence on the Red Hand threat',
			'Coordinate defense preparations',
		],
		relationships: [
			{ name: 'Norro', type: 'Colleague', description: 'Works with Councilman Norro on town security.' },
			{
				name: 'Kat and Yoghurt',
				type: 'Operatives',
				description: 'Two exiled thieves working as her intelligence gatherers.',
			},
		],
		encounters: [
			{ session: 1, description: 'Briefed party on raider activity and the Witchwood.' },
			{ session: 2, description: 'Rewarded party for clearing the bridge ambush.' },
			{ session: 3, description: 'Met party in tollhouse basement to discuss attacks.' },
		],
	},
	{
		id: 'norro',
		name: 'Councilman Norro',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Unknown',
		class: 'Unknown',
		role: 'Town Councilor',
		description: "A councilman of Drellin's Ferry who works with Soranna on town security matters.",
		location: "Drellin's Ferry",
		relationships: [{ name: 'Soranna', type: 'Colleague', description: 'Coordinates with her on security issues.' }],
	},
	{
		id: 'wyrmlord-koth',
		name: 'Wyrmlord Koth',
		affinity: 'Antagonist',
		status: 'Alive',
		race: 'Unknown',
		class: 'Warlord',
		role: 'Tribal Leader',
		description: 'A mysterious warlord gathering tribes for a "Day of Ruin." Commands hobgoblin and orc forces.',
		personality: 'Unknown, but orchestrates large-scale coordinated attacks.',
		background:
			'Gathering various tribes including hobgoblins, orcs, and other creatures. Not the ultimate leader of the plot.',
		goals: [
			'Unite tribes for the Day of Ruin',
			'Coordinate raids on settlements',
			'Serve a higher power in the Red Hand',
		],
	},
	{
		id: 'sergeant-hersk',
		name: 'Sergeant Hersk',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Unknown',
		class: 'Warrior',
		role: 'Town Guard Sergeant',
		description: "A sergeant in Drellin's Ferry who briefed the party on recent raids and the Witchwood.",
		location: "Drellin's Ferry",
		encounters: [{ session: 1, description: 'Briefed party on raids and undead rumors in the Witchwood.' }],
	},
	{
		id: 'brother-denny',
		name: 'Brother Denny',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Human',
		class: 'Cleric',
		role: 'Priest of Pelor',
		description: "A priest at the Shrine of Pelor in Drellin's Ferry.",
		location: "Drellin's Ferry - Shrine of Pelor",
		encounters: [{ session: 1, description: 'Received offerings from Norr and Soshi.' }],
	},
	{
		id: 'sertieren',
		name: 'Sertieren',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Unknown',
		class: 'Wizard',
		role: 'Local Wizard',
		description:
			'An elderly, eccentric wizard living in a mansion in Drellin\'s Ferry. Former adventurer with the "Crazy Hogs" party.',
		personality: 'Rambling, knowledgeable, pragmatic. Sees the coming danger and plans to leave.',
		background:
			'Former adventurer who traveled with Kalistra before she joined the Brotherhood. They had a falling out over her willingness to cause collateral damage.',
		location: "Drellin's Ferry - Sertieren's Manor",
		goals: ["Leave Drellin's Ferry before the storm breaks", 'Study magical phenomena'],
		relationships: [
			{
				name: 'Kalistra',
				type: 'Former Companion',
				description: 'Former adventuring companion. Stole her spellbook to stop her from collapsing a settlement.',
			},
		],
		items: ['Various magical components', 'Containment spheres'],
		encounters: [
			{ session: 1, description: 'Rambled about Chronomancers of Krynn and magical nexuses.' },
			{ session: 3, description: 'Sold containment spheres to the party.' },
			{ session: 5, description: 'Bought Storm Dust and other materials, warned of coming danger.' },
		],
	},
	{
		id: 'tarma',
		name: 'Tarma',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Dwarf',
		class: 'Unknown',
		role: 'Innkeeper',
		description: 'The jovial dwarven proprietress of the Old Bridge Inn (also called Green Apple Inn).',
		personality: 'Friendly, practical, enjoys reading romance novels.',
		location: "Drellin's Ferry - Old Bridge Inn / Green Apple Inn",
		encounters: [
			{ session: 2, description: "Provided breakfast before the party's journey." },
			{ session: 3, description: "Informed party about Anya's disappearance." },
			{ session: 6, description: 'Served experimental stew that granted temporary HP.' },
		],
	},
	{
		id: 'jun-takashi',
		name: 'Jun Takashi',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Human',
		class: 'Unknown',
		role: 'Winter Rose Mercenary',
		description: 'A mercenary of the Winter Rose company. Gave Olek a magical tattoo to call for help.',
		location: 'Traveling (last seen at Old Bridge Inn)',
		items: ['Magical communication tattoo'],
		encounters: [
			{ session: 2, description: 'Warned party about spider demon and gave Olek emergency contact tattoo.' },
		],
		relationships: [
			{
				name: 'Hans Mariner',
				type: 'Commander',
				description: "Captain of the Lion's Guard in Brindol, would reward for spider demon.",
			},
		],
	},
	{
		id: 'kat',
		name: 'Kat',
		affinity: 'Neutral',
		status: 'Alive',
		race: 'Tiefling',
		class: 'Rogue',
		role: 'Exiled Thief / Intelligence Operative',
		description:
			'An unremarkable-looking tiefling with an unusual passion for cats. Former Thieves Guild member exiled for incompetence.',
		personality: 'Forgettable appearance, cat enthusiast, somewhat incompetent.',
		location: "Drellin's Ferry",
		items: ['Multiple cats in magical globes', 'Large tiger'],
		goals: ['Pay off debts (needs 2 gold pieces)', 'Avoid Winter Rose mercenaries'],
		relationships: [
			{ name: 'Yoghurt', type: 'Partner', description: 'Fellow exiled thief working together.' },
			{ name: 'Soranna', type: 'Employer', description: 'Works for her gathering intelligence.' },
		],
		encounters: [{ session: 3, description: 'Met party to discuss cave system beneath the city.' }],
	},
	{
		id: 'yoghurt',
		name: 'Yoghurt',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Half-Ogre',
		class: 'Rogue/Assassin',
		role: 'Exiled Thief / Intelligence Operative',
		description:
			'A lactose-intolerant half-ogre assassin. Former Thieves Guild member exiled for incompetence. Wears elegant kimono with two katanas.',
		personality: 'Simple-minded but loyal when properly motivated.',
		location: "Drellin's Ferry / Traveling",
		items: ['Kimono', 'Two katanas'],
		relationships: [
			{ name: 'Kat', type: 'Partner', description: 'Fellow exiled thief working together.' },
			{ name: 'Soranna', type: 'Employer', description: 'Works for her gathering intelligence.' },
			{ name: 'Raven Master', type: 'Superior', description: 'Reports to a Raven master in the thieves guild.' },
		],
		encounters: [
			{ session: 3, description: 'Met party to discuss cave system.' },
			{
				session: 8,
				description: 'Followed party to fortress, killed two shadow-clad enemies, delivered letter to Soranna.',
			},
		],
	},
	{
		id: 'avarthel',
		name: 'Avarthel',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Unknown',
		class: 'Druid (Circle of the Land)',
		role: 'Local Druid',
		description: "A druid who maintains a grove near Drellin's Ferry with proximity to the Feywild.",
		personality: 'Protective of ecosystems, refuses to hatch dangerous creatures.',
		location: "Mountains (formerly Drellin's Ferry grove)",
		background: 'Left for the mountains with his followers a month before Session 3.',
		items: ['Hydra eggs (in his care)'],
		encounters: [
			{ session: 1, description: 'Warned about Wrath Keep, a cursed fortress guarded by undead.' },
			{
				session: 3,
				description: 'Refused to hatch hydra eggs, provided information about Thylacoleos and treated Anya.',
			},
		],
	},
	{
		id: 'anya',
		name: 'Anya',
		affinity: 'Neutral',
		status: 'Alive',
		race: 'Human',
		class: 'None',
		role: 'Tavern Assistant',
		description:
			'A 17-year-old human girl with striking red hair and freckles. Former assistant at the Green Apple Inn.',
		personality: 'Troubled, vulnerable.',
		background:
			'Had a relationship with Lem that turned serious on her side but was casual to him. Became pregnant and attempted self-harm.',
		location: 'With Avarthel in the mountains (receiving care)',
		height: '1.8 meters',
		relationships: [
			{ name: 'Lem', type: 'Former Lover', description: 'Had a one-sided serious relationship with him.' },
		],
		encounters: [{ session: 3, description: 'Rescued by party in distressed state, taken to Avarthel for healing.' }],
	},
	{
		id: 'lem',
		name: 'Lem',
		affinity: 'Neutral',
		status: 'Alive',
		race: 'Human',
		class: 'Guard',
		role: 'Town Guard',
		description: 'A rotund 19-year-old human guard standing 1.5 meters tall.',
		personality: 'Callous, immature, treated relationships casually.',
		location: "Drellin's Ferry - Barracks Infirmary",
		background: 'Had a casual relationship with Anya that became serious on her side. Was attacked by worg riders.',
		relationships: [{ name: 'Anya', type: 'Former Lover', description: "Didn't take their relationship seriously." }],
		encounters: [
			{ session: 3, description: 'Recovering in infirmary after worg attack, provided information about Anya.' },
		],
	},
	{
		id: 'jareth',
		name: 'Jareth of House Corzina',
		affinity: 'Neutral',
		status: 'Alive',
		race: 'Drow',
		class: 'Unknown',
		role: 'Exiled Drow',
		description:
			"A remarkably muscular drow who uses illusion magic to appear clothed. Sent to Drellin's Ferry 20 years ago.",
		personality: 'Patient, follows orders from his matron.',
		background:
			"Sent by Matron Zaya 20 years ago to wait for a specific signal that hasn't come yet. From a matriarchal drow society.",
		location: "Drellin's Ferry - Shopping District",
		relationships: [{ name: 'Matron Zaya', type: 'Superior', description: 'Awaiting her signal to return or act.' }],
		encounters: [
			{ session: 3, description: 'Met party in shopping district, sold healing potions.' },
			{ session: 6, description: 'Bought crystals from party, informed them about fake pearls.' },
		],
	},
	{
		id: 'turiados',
		name: 'Commander Turiados',
		affinity: 'Neutral',
		status: 'Alive',
		race: 'Unknown (Sahuagin-marked)',
		class: 'Warrior/Shaman',
		role: "Co-Commander of Leviathan's Hall",
		description: 'A terrifying 7-foot-tall warrior covered in Sahuagin shaman tattoos. Formerly of the Order of Inos.',
		personality: 'Intimidating, pragmatic, bound by honor.',
		background: 'Former convict from a penal colony, freed by General Lee. Now serves Queen Bianca.',
		location: "The Leviathan's Hall (pirate ship)",
		items: [
			'Breaker of Hulls (stolen cutlass from Brotherhood)',
			'Broken compass that points to greatest desires',
			'Wyvern hide coat',
			'Sea snake belt',
		],
		relationships: [
			{ name: 'Bianca', type: 'Co-Commander', description: 'Shares command of the ship.' },
			{ name: 'General Lee', type: 'Former Commander', description: 'The mercenary who freed him from slavery.' },
		],
		encounters: [{ session: 5, description: 'Rescued party from sea, demanded 20% fee, offered deal to kill Sandro.' }],
	},
	{
		id: 'bianca',
		name: 'Commander Bianca / Queen Bianca Corina',
		affinity: 'Neutral',
		status: 'Alive',
		race: 'Fey-touched',
		class: 'Wizard (Multi-school)',
		role: 'Co-Commander / Exiled Queen',
		description: 'Last descendant and true Queen of Pelagos. Fey-touched with lightning-veined eyes.',
		personality: 'Regal, determined, protective of her crew.',
		background:
			'Her father was killed and throne stolen by necromancer Sandro. Escaped with loyal followers and now commands a pirate-paladin crew.',
		location: "The Leviathan's Hall (pirate ship)",
		items: [
			'Winder (stolen storm-forged glass blade from Brotherhood)',
			'Multiple rings representing different schools of magic',
		],
		goals: ['Reclaim her throne from Sandro', 'Return to Pelagos', 'Find General Lee'],
		relationships: [
			{ name: 'Turiados', type: 'Co-Commander', description: 'Shares command of the ship.' },
			{ name: 'General Lee', type: 'Missing', description: 'She wishes he was present to help navigate.' },
			{ name: 'Glass', type: 'Advisor', description: 'Ice Elemental she freed, now her quartermaster.' },
		],
		encounters: [
			{
				session: 5,
				description:
					"Rescued party from sea, attempted to probe Soshi's mind, attacked Bonnie for dropping cursed coin.",
			},
		],
	},
	{
		id: 'glass',
		name: 'Glass',
		affinity: 'Neutral',
		status: 'Alive',
		race: 'Ice Elemental',
		class: 'Unknown',
		role: 'Quartermaster / Negotiator',
		description: 'A massive Ice Elemental who speaks with agonizing slowness except when conducting business.',
		personality: 'Loyal, methodical, all-business when negotiating.',
		background: 'Freed from shackles by Bianca, pledged blood loyalty to her.',
		location: "The Leviathan's Hall",
		relationships: [{ name: 'Bianca', type: 'Freed by', description: 'Pledged loyalty after she freed him.' }],
		encounters: [{ session: 5, description: 'Negotiated the 20% rescue fee, explained cursed coin mechanics.' }],
	},
	{
		id: 'vandal',
		name: 'Vandal',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Unknown',
		class: 'Caster',
		role: 'Winter Rose Mercenary',
		description: 'One of the Winter Rose mercenaries. Known as "Vandal" by Kat and Yoghurt.',
		personality: 'Capable, survivor.',
		location: 'Traveling',
		encounters: [
			{ session: 3, description: 'Shared information about raptors and Thylacoleos.' },
			{ session: 4, description: 'Caused controlled collapses to free ship from underground chamber.' },
			{ session: 5, description: 'Rescued with party, paid rescue fee to pirates.' },
		],
	},
	{
		id: 'summoner',
		name: 'Summoner',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Unknown',
		class: 'Summoner',
		role: 'Winter Rose Mercenary',
		description:
			'One of the Winter Rose mercenaries. Known as "Summoner" by Kat and Yoghurt. Can summon magical dolphins.',
		location: 'Traveling',
		encounters: [
			{ session: 3, description: 'Shared information with party at tavern, involved in tavern brawl.' },
			{ session: 4, description: 'Took different tunnel path in underground complex.' },
			{ session: 5, description: 'Summoned dolphins to rescue party members from drowning.' },
		],
	},
	{
		id: 'kalistra',
		name: 'Kalistra',
		affinity: 'Antagonist (complicated)',
		status: 'Deceased',
		race: 'Unknown',
		class: 'Wizard (Alteration/Transmutation)',
		role: 'Former Brotherhood Teacher / Rogue Mage',
		description:
			'A harsh instructor from the Brotherhood who specialized in alteration magic and creatures. Left 10 years ago.',
		personality: 'Pragmatic to the point of ruthlessness, willing to cause collateral damage.',
		background:
			'Former adventurer with the "Crazy Hogs." Left Brotherhood 10 years ago. Created arena and breeding program for creatures. Used her life to contain the Null Brand artifact.',
		location: 'Deceased - Underground vault',
		items: ['Ledger (partially burned and magically obscured)', 'Laboratory notes'],
		goals: ['Operated creature breeding program', 'Researched Null Brand artifact', 'Contain corruption before death'],
		relationships: [
			{
				name: 'Sertieren',
				type: 'Former Companion',
				description: 'Adventured together before falling out over ethics.',
			},
			{
				name: 'Norr',
				type: 'Former Student',
				description: 'Taught her alteration magic using harsh "mind spiking" methods.',
			},
			{ name: 'Kilgor', type: 'Associate', description: 'Was sending creatures to him for "Festival of Life."' },
		],
		encounters: [
			{ session: 4, description: 'Her ledger found in underground complex.' },
			{ session: 7, description: 'Found dead, fused to Null Brand artifact, containing its corruption.' },
		],
	},
	{
		id: 'kilgor',
		name: 'Kilgor',
		affinity: 'Antagonist',
		status: 'Alive',
		race: 'Unknown',
		class: 'Unknown',
		role: 'Creature Collector',
		description: 'A figure who was receiving creatures from Kalistra for something called the "Festival of Life."',
		background: 'Sent three harpies that Kalistra suspected were spies. Associated with creature trafficking.',
		goals: ['Collect creatures for Festival of Life', "Spy on Kalistra's operation"],
		relationships: [{ name: 'Kalistra', type: 'Associate', description: 'Received creatures from her operation.' }],
	},
	{
		id: 'sandro',
		name: 'Sandro',
		affinity: 'Antagonist',
		status: 'Alive',
		race: 'Unknown',
		class: 'Necromancer',
		role: 'Tyrant King / Necromancer',
		description:
			"A powerful necromancer who killed Bianca's father and stole the throne of Pelagos. Turned entire villages to zombies.",
		personality: 'Evil, power-hungry.',
		background:
			'Came from nowhere during Pelagos civil war, killed the king, and seized power. From Lustria continent.',
		location: 'Unknown (last known: Pelagos throne, now somewhere in the region)',
		goals: ['Maintain control of Pelagos', 'Expand necromantic power'],
		relationships: [
			{ name: 'Bianca', type: 'Enemy', description: 'Killed her father and stole her throne.' },
			{ name: 'Turiados', type: 'Enemy', description: 'Turiados seeks to kill him.' },
		],
	},
	{
		id: 'general-lee',
		name: 'General Lee',
		affinity: 'Ally',
		status: 'Unknown',
		race: 'Unknown',
		class: 'Warrior',
		role: 'Mercenary Commander',
		description:
			"Former convict who became commander of mercenaries. Led the breakout from penal colony and freed Bianca's crew.",
		personality: 'Capable leader, strategic thinker.',
		background:
			'Former convict from mining penal colony. Led successful prison break and helped Bianca steal her flagship.',
		location: 'Unknown (Missing)',
		relationships: [
			{ name: 'Bianca', type: 'Ally', description: 'She misses his counsel and leadership.' },
			{ name: 'Turiados', type: 'Former Commander', description: 'Led him and others in prison break.' },
		],
	},
	{
		id: 'hans-mariner',
		name: 'Captain Hans Mariner',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Unknown',
		class: 'Unknown',
		role: "Captain of the Lion's Guard",
		description: "Captain of the Lion's Guard in Brindol. Offers rewards for defeating dangerous creatures.",
		location: 'Brindol',
		encounters: [{ session: 2, description: 'Mentioned by Jun Takashi as offering reward for spider demon.' }],
	},
	{
		id: 'marise-curs',
		name: 'Marise Curs',
		affinity: 'Neutral',
		status: 'Alive',
		race: 'Unknown',
		class: 'Unknown',
		role: 'Pirate',
		description: "A peg-legged pirate on the Leviathan's Hall with an unusual living mug.",
		personality: 'Talkative when drunk, loyal to Bianca.',
		location: "The Leviathan's Hall",
		items: ['Living tentacle mug'],
		background: 'Former slave in penal colony, freed by General Lee. Bound by blood to House Corina.',
		encounters: [{ session: 5, description: "Talked to Bonnie about the ship's history and General Lee." }],
	},
	{
		id: 'bardin-cratcho',
		name: 'Bardin Cratcho',
		affinity: 'Neutral',
		status: 'Alive',
		race: 'Dwarf',
		class: 'Artificer/Smith',
		role: "Ship's Runesmith",
		description:
			'A heavily augmented dwarf who tempers runes onto weapons. Claims to have eaten molten slag to prove his forge quality.',
		personality: 'Proud, expensive, skilled.',
		location: "The Leviathan's Hall - Forge",
		encounters: [{ session: 5, description: "Offered to rune Kaedin's sword for 50 gold." }],
		relationships: [{ name: 'Efreeti', type: 'Colleague', description: 'Works with an Efreeti at the forge.' }],
	},
	{
		id: 'nels-huto',
		name: 'Nels Huto',
		affinity: 'Unknown',
		status: 'Unknown',
		race: 'Unknown',
		class: 'Unknown',
		role: "Previous Owner of Dead Man's Boots",
		description: "Last person known to possess the Dead Man's Boots artifact.",
		location: 'Somewhere in the Witchwood',
		items: ["Dead Man's Boots (artifact)"],
		encounters: [{ session: 1, description: 'Mentioned by Sorana as last holder of the boots.' }],
	},
	{
		id: 'dwarf-armorer',
		name: 'Dwarf Armorer',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Dwarf',
		class: 'Blacksmith',
		role: 'Master Armorer',
		description: 'A tiny dwarf who works inside on scaffolding, creating high-quality armor.',
		personality: 'Skilled, respects Norro, professional.',
		location: "Drellin's Ferry - Armorer's Forge",
		relationships: [
			{ name: 'Gnome Woman', type: 'Business Partner', description: 'Works the large forge outside.' },
			{ name: 'Norro', type: 'Respects', description: 'Likes Norro and honors his discount notes.' },
		],
		encounters: [{ session: 6, description: 'Sold and reinforced armor for the party using Thylacoleo pelts.' }],
	},
	{
		id: 'loic',
		name: 'Loic',
		affinity: 'Ally',
		status: 'Alive',
		race: 'Phoenix',
		class: 'Magical Creature',
		role: 'Guardian Spirit',
		description: "A phoenix residing in Avarthel's grove who can heal with tears.",
		location: "Avarthel's Grove",
		encounters: [{ session: 3, description: 'Shed healing tears on Anya to stabilize her condition.' }],
	},
];
